repos:
- repo: local
  hooks:
  - id: generate
    name: Generate
    language: system
    entry: bash -c "./generate.sh"
    files: '^(\.generator/.*|\.pre-commit-config\.yaml|Makefile|\tests/scenarios/features/.*)'
    pass_filenames: false
    verbose: true
  - id: generator
    name: generator
    language: python
    entry: bash -c "cd .generator && poetry install && poetry run python -m generator ./schemas/v1/openapi.yaml ./schemas/v2/openapi.yaml -o ../src/"
    files: "^.generator/.*"
    stages: [manual]
    pass_filenames: false
    additional_dependencies:
      - "poetry"
  - id: format
    name: Format
    language: system
    entry: cargo fmt
    pass_filenames: false
    stages: [manual]
  - id: lint
    name: Lint
    entry: cargo check
    language: system
    pass_filenames: false
    stages: [manual]
  - id: license-check
    name: Check license file
    entry: bash -c "scripts/license-check.sh"
    language: system
    stages: ["manual"]
    verbose: true
    pass_filenames: false
