repos:
- repo: local
  hooks:
  - id: format
    name: Format
    language: system
    entry: ./format.sh
    pass_filenames: false
  - id: lint
    name: Lint
    entry: cargo check
    language: system
    pass_filenames: false
    stages: [manual]
  - id: license-check
    name: Check license file
    entry: bash -c "scripts/license-check.sh"
    language: system
    stages: ["manual"]
    verbose: true
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-case-conflict
