// Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2019-Present Datadog, Inc.
use serde::de::{Error, MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::skip_serializing_none;
use std::fmt::{self, Formatter};

/// A message containing one response to a timeseries query made with timeseries formula query request.
#[non_exhaustive]
#[skip_serializing_none]
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct TimeseriesFormulaQueryResponse {
    /// A message containing the response to a timeseries query.
    #[serde(rename = "data")]
    pub data: Option<crate::datadogV2::model::TimeseriesResponse>,
    /// The error generated by the request.
    #[serde(rename = "errors")]
    pub errors: Option<String>,
    #[serde(skip)]
    #[serde(default)]
    pub(crate) _unparsed: bool,
}

impl TimeseriesFormulaQueryResponse {
    pub fn new() -> TimeseriesFormulaQueryResponse {
        TimeseriesFormulaQueryResponse {
            data: None,
            errors: None,
            _unparsed: false,
        }
    }

    pub fn data(mut self, value: crate::datadogV2::model::TimeseriesResponse) -> Self {
        self.data = Some(value);
        self
    }

    pub fn errors(mut self, value: String) -> Self {
        self.errors = Some(value);
        self
    }
}

impl Default for TimeseriesFormulaQueryResponse {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de> Deserialize<'de> for TimeseriesFormulaQueryResponse {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct TimeseriesFormulaQueryResponseVisitor;
        impl<'a> Visitor<'a> for TimeseriesFormulaQueryResponseVisitor {
            type Value = TimeseriesFormulaQueryResponse;

            fn expecting(&self, f: &mut Formatter<'_>) -> fmt::Result {
                f.write_str("a mapping")
            }

            fn visit_map<M>(self, mut map: M) -> Result<Self::Value, M::Error>
            where
                M: MapAccess<'a>,
            {
                let mut data: Option<crate::datadogV2::model::TimeseriesResponse> = None;
                let mut errors: Option<String> = None;
                let mut _unparsed = false;

                while let Some((k, v)) = map.next_entry::<String, serde_json::Value>()? {
                    match k.as_str() {
                        "data" => {
                            if v.is_null() {
                                continue;
                            }
                            data = Some(serde_json::from_value(v).map_err(M::Error::custom)?);
                        }
                        "errors" => {
                            if v.is_null() {
                                continue;
                            }
                            errors = Some(serde_json::from_value(v).map_err(M::Error::custom)?);
                        }
                        &_ => {}
                    }
                }

                let content = TimeseriesFormulaQueryResponse {
                    data,
                    errors,
                    _unparsed,
                };

                Ok(content)
            }
        }

        deserializer.deserialize_any(TimeseriesFormulaQueryResponseVisitor)
    }
}
