info:
  contact:
    name: Datadog Support
    url: https://www.datadoghq.com/support/
    email: support@datadoghq.com
  description: Collection of all Datadog Public endpoints.
  title: Datadog API V1 Collection
  version: "1.0"
openapi: 3.0.0
servers:
  - url: https://{subdomain}.{site}
    variables:
      subdomain:
        default: api
        description: The subdomain where the API is deployed.
      site:
        default: datadoghq.com
        description: The regional site for a Datadog customer.
        enum:
          - datadoghq.com
          - us3.datadoghq.com
          - us5.datadoghq.com
          - ap1.datadoghq.com
          - datadoghq.eu
          - ddog-gov.com
  - url: "{protocol}://{name}"
    variables:
      protocol:
        default: https
        description: The protocol for accessing the API.
      name:
        default: api.datadoghq.com
        description: Full site DNS name.
  - url: https://{subdomain}.{site}
    variables:
      subdomain:
        default: api
        description: The subdomain where the API is deployed.
      site:
        default: datadoghq.com
        description: Any Datadog deployment.
x-group-parameters: true
