// Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2019-Present Datadog, Inc.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeseriesFormulaQueryResponse {
    /// A message containing the response to a timeseries query.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: TimeseriesResponse,
    /// The error generated by the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: String,
}

