/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiKeysResponse : Response for a list of API keys.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKeysResponse {
    /// Array of API keys.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::PartialApiKey>>,
    /// Array of objects related to the API key.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::ApiKeyResponseIncludedItem>>,
}

impl ApiKeysResponse {
    /// Response for a list of API keys.
    pub fn new() -> ApiKeysResponse {
        ApiKeysResponse {
            data: None,
            included: None,
        }
    }
}


