/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiKeyUpdateRequest : Request used to update an API key.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKeyUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::ApiKeyUpdateData>,
}

impl ApiKeyUpdateRequest {
    /// Request used to update an API key.
    pub fn new(data: crate::models::ApiKeyUpdateData) -> ApiKeyUpdateRequest {
        ApiKeyUpdateRequest {
            data: Box::new(data),
        }
    }
}


