/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiErrorResponse : API error response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiErrorResponse {
    /// A list of errors.
    #[serde(rename = "errors")]
    pub errors: Vec<String>,
}

impl ApiErrorResponse {
    /// API error response.
    pub fn new(errors: Vec<String>) -> ApiErrorResponse {
        ApiErrorResponse {
            errors,
        }
    }
}


