/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationKeyCreateAttributes : Attributes used to create an application Key.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationKeyCreateAttributes {
    /// Name of the application key.
    #[serde(rename = "name")]
    pub name: String,
    /// Array of scopes to grant the application key.
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<Vec<String>>>,
}

impl ApplicationKeyCreateAttributes {
    /// Attributes used to create an application Key.
    pub fn new(name: String) -> ApplicationKeyCreateAttributes {
        ApplicationKeyCreateAttributes {
            name,
            scopes: None,
        }
    }
}


