/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationKeysSort : Sorting options

/// Sorting options
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationKeysSort {
    #[serde(rename = "created_at")]
    CREATED_AT_ASCENDING,
    #[serde(rename = "-created_at")]
    CREATED_AT_DESCENDING,
    #[serde(rename = "last4")]
    LAST4_ASCENDING,
    #[serde(rename = "-last4")]
    LAST4_DESCENDING,
    #[serde(rename = "name")]
    NAME_ASCENDING,
    #[serde(rename = "-name")]
    NAME_DESCENDING,

}

impl ToString for ApplicationKeysSort {
    fn to_string(&self) -> String {
        match self {
            Self::CREATED_AT_ASCENDING => String::from("created_at"),
            Self::CREATED_AT_DESCENDING => String::from("-created_at"),
            Self::LAST4_ASCENDING => String::from("last4"),
            Self::LAST4_DESCENDING => String::from("-last4"),
            Self::NAME_ASCENDING => String::from("name"),
            Self::NAME_DESCENDING => String::from("-name"),
        }
    }
}

impl Default for ApplicationKeysSort {
    fn default() -> ApplicationKeysSort {
        Self::CREATED_AT_ASCENDING
    }
}




