/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationKeyUpdateAttributes : Attributes used to update an application Key.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationKeyUpdateAttributes {
    /// Name of the application key.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Array of scopes to grant the application key.
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<Vec<String>>>,
}

impl ApplicationKeyUpdateAttributes {
    /// Attributes used to update an application Key.
    pub fn new() -> ApplicationKeyUpdateAttributes {
        ApplicationKeyUpdateAttributes {
            name: None,
            scopes: None,
        }
    }
}


