/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationKeyCreateRequest : Request used to create an application key.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationKeyCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::ApplicationKeyCreateData>,
}

impl ApplicationKeyCreateRequest {
    /// Request used to create an application key.
    pub fn new(data: crate::models::ApplicationKeyCreateData) -> ApplicationKeyCreateRequest {
        ApplicationKeyCreateRequest {
            data: Box::new(data),
        }
    }
}


