/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationKeysType : Application Keys resource type.

/// Application Keys resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationKeysType {
    #[serde(rename = "application_keys")]
    APPLICATION_KEYS,

}

impl ToString for ApplicationKeysType {
    fn to_string(&self) -> String {
        match self {
            Self::APPLICATION_KEYS => String::from("application_keys"),
        }
    }
}

impl Default for ApplicationKeysType {
    fn default() -> ApplicationKeysType {
        Self::APPLICATION_KEYS
    }
}




