/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogsResponseLinks : Links attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogsResponseLinks {
    /// Link for the next set of results. Note that the request can also be made using the POST endpoint.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl AuditLogsResponseLinks {
    /// Links attributes.
    pub fn new() -> AuditLogsResponseLinks {
        AuditLogsResponseLinks {
            next: None,
        }
    }
}


