/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogsEvent : Object description of an Audit Logs event after it is processed and stored by Datadog.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogsEvent {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::AuditLogsEventAttributes>>,
    /// Unique ID of the event.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::AuditLogsEventType>,
}

impl AuditLogsEvent {
    /// Object description of an Audit Logs event after it is processed and stored by Datadog.
    pub fn new() -> AuditLogsEvent {
        AuditLogsEvent {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


