/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuditLogsWarning : Warning message indicating something that went wrong with the query.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditLogsWarning {
    /// Unique code for this type of warning.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Detailed explanation of this specific warning.
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Short human-readable summary of the warning.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl AuditLogsWarning {
    /// Warning message indicating something that went wrong with the query.
    pub fn new() -> AuditLogsWarning {
        AuditLogsWarning {
            code: None,
            detail: None,
            title: None,
        }
    }
}


