/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingResponse : AuthN Mapping response from the API.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthNMappingResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::AuthNMapping>>,
    /// Included data in the AuthN Mapping response.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::AuthNMappingIncluded>>,
}

impl AuthNMappingResponse {
    /// AuthN Mapping response from the API.
    pub fn new() -> AuthNMappingResponse {
        AuthNMappingResponse {
            data: None,
            included: None,
        }
    }
}


