/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingsType : AuthN Mappings resource type.

/// AuthN Mappings resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthNMappingsType {
    #[serde(rename = "authn_mappings")]
    AUTHN_MAPPINGS,

}

impl ToString for AuthNMappingsType {
    fn to_string(&self) -> String {
        match self {
            Self::AUTHN_MAPPINGS => String::from("authn_mappings"),
        }
    }
}

impl Default for AuthNMappingsType {
    fn default() -> AuthNMappingsType {
        Self::AUTHN_MAPPINGS
    }
}




