/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingUpdateAttributes : Key/Value pair of attributes used for update request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthNMappingUpdateAttributes {
    /// Key portion of a key/value pair of the attribute sent from the Identity Provider.
    #[serde(rename = "attribute_key", skip_serializing_if = "Option::is_none")]
    pub attribute_key: Option<String>,
    /// Value portion of a key/value pair of the attribute sent from the Identity Provider.
    #[serde(rename = "attribute_value", skip_serializing_if = "Option::is_none")]
    pub attribute_value: Option<String>,
}

impl AuthNMappingUpdateAttributes {
    /// Key/Value pair of attributes used for update request.
    pub fn new() -> AuthNMappingUpdateAttributes {
        AuthNMappingUpdateAttributes {
            attribute_key: None,
            attribute_value: None,
        }
    }
}


