/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingUpdateRequest : Request to update an AuthN Mapping.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthNMappingUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::AuthNMappingUpdateData>,
}

impl AuthNMappingUpdateRequest {
    /// Request to update an AuthN Mapping.
    pub fn new(data: crate::models::AuthNMappingUpdateData) -> AuthNMappingUpdateRequest {
        AuthNMappingUpdateRequest {
            data: Box::new(data),
        }
    }
}


