/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingIncluded : Included data in the AuthN Mapping response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthNMappingIncluded {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::RoleAttributes>>,
    /// The unique identifier of the role.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::RolesType,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::RoleResponseRelationships>>,
}

impl AuthNMappingIncluded {
    /// Included data in the AuthN Mapping response.
    pub fn new(id: String, r#type: crate::models::RolesType) -> AuthNMappingIncluded {
        AuthNMappingIncluded {
            attributes: None,
            id,
            r#type,
            relationships: None,
        }
    }
}


