/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthNMappingAttributes : Attributes of AuthN Mapping.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthNMappingAttributes {
    /// Key portion of a key/value pair of the attribute sent from the Identity Provider.
    #[serde(rename = "attribute_key", skip_serializing_if = "Option::is_none")]
    pub attribute_key: Option<String>,
    /// Value portion of a key/value pair of the attribute sent from the Identity Provider.
    #[serde(rename = "attribute_value", skip_serializing_if = "Option::is_none")]
    pub attribute_value: Option<String>,
    /// Creation time of the AuthN Mapping.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time of last AuthN Mapping modification.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    /// The ID of the SAML assertion attribute.
    #[serde(rename = "saml_assertion_attribute_id", skip_serializing_if = "Option::is_none")]
    pub saml_assertion_attribute_id: Option<String>,
}

impl AuthNMappingAttributes {
    /// Attributes of AuthN Mapping.
    pub fn new() -> AuthNMappingAttributes {
        AuthNMappingAttributes {
            attribute_key: None,
            attribute_value: None,
            created_at: None,
            modified_at: None,
            saml_assertion_attribute_id: None,
        }
    }
}


