/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppPipelineEventPipelineStatus : The final status of the pipeline.

/// The final status of the pipeline.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CiAppPipelineEventPipelineStatus {
    #[serde(rename = "success")]
    SUCCESS,
    #[serde(rename = "error")]
    ERROR,
    #[serde(rename = "canceled")]
    CANCELED,
    #[serde(rename = "skipped")]
    SKIPPED,
    #[serde(rename = "blocked")]
    BLOCKED,

}

impl ToString for CiAppPipelineEventPipelineStatus {
    fn to_string(&self) -> String {
        match self {
            Self::SUCCESS => String::from("success"),
            Self::ERROR => String::from("error"),
            Self::CANCELED => String::from("canceled"),
            Self::SKIPPED => String::from("skipped"),
            Self::BLOCKED => String::from("blocked"),
        }
    }
}

impl Default for CiAppPipelineEventPipelineStatus {
    fn default() -> CiAppPipelineEventPipelineStatus {
        Self::SUCCESS
    }
}




