/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppTestsAggregateRequest : The object sent with the request to retrieve aggregation buckets of test events from your organization.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppTestsAggregateRequest {
    /// The list of metrics or timeseries to compute for the retrieved buckets.
    #[serde(rename = "compute", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Vec<crate::models::CiAppCompute>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::CiAppTestsQueryFilter>>,
    /// The rules for the group-by.
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<crate::models::CiAppTestsGroupBy>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::CiAppQueryOptions>>,
}

impl CiAppTestsAggregateRequest {
    /// The object sent with the request to retrieve aggregation buckets of test events from your organization.
    pub fn new() -> CiAppTestsAggregateRequest {
        CiAppTestsAggregateRequest {
            compute: None,
            filter: None,
            group_by: None,
            options: None,
        }
    }
}


