/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppTestsAnalyticsAggregateResponse : The response object for the test events aggregate API endpoint.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppTestsAnalyticsAggregateResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::CiAppTestsAggregationBucketsResponse>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::CiAppResponseLinks>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::CiAppResponseMetadata>>,
}

impl CiAppTestsAnalyticsAggregateResponse {
    /// The response object for the test events aggregate API endpoint.
    pub fn new() -> CiAppTestsAnalyticsAggregateResponse {
        CiAppTestsAnalyticsAggregateResponse {
            data: None,
            links: None,
            meta: None,
        }
    }
}


