/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppPipelineEventParentPipeline : If the pipeline is triggered as child of another pipeline, this should contain the details of the parent pipeline.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppPipelineEventParentPipeline {
    /// UUID of a pipeline.
    #[serde(rename = "id")]
    pub id: String,
    /// The URL to look at the pipeline in the CI provider UI.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl CiAppPipelineEventParentPipeline {
    /// If the pipeline is triggered as child of another pipeline, this should contain the details of the parent pipeline.
    pub fn new(id: String) -> CiAppPipelineEventParentPipeline {
        CiAppPipelineEventParentPipeline {
            id,
            url: None,
        }
    }
}


