/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppTestEventTypeName : Type of the event.

/// Type of the event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CiAppTestEventTypeName {
    #[serde(rename = "citest")]
    CITEST,

}

impl ToString for CiAppTestEventTypeName {
    fn to_string(&self) -> String {
        match self {
            Self::CITEST => String::from("citest"),
        }
    }
}

impl Default for CiAppTestEventTypeName {
    fn default() -> CiAppTestEventTypeName {
        Self::CITEST
    }
}




