/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppPipelineEventsRequest : The request for a pipelines search.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppPipelineEventsRequest {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::CiAppPipelinesQueryFilter>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::CiAppQueryOptions>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<crate::models::CiAppQueryPageOptions>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<crate::models::CiAppSort>,
}

impl CiAppPipelineEventsRequest {
    /// The request for a pipelines search.
    pub fn new() -> CiAppPipelineEventsRequest {
        CiAppPipelineEventsRequest {
            filter: None,
            options: None,
            page: None,
            sort: None,
        }
    }
}


