/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppCreatePipelineEventRequest : Request object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppCreatePipelineEventRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::CiAppCreatePipelineEventRequestData>>,
}

impl CiAppCreatePipelineEventRequest {
    /// Request object.
    pub fn new() -> CiAppCreatePipelineEventRequest {
        CiAppCreatePipelineEventRequest {
            data: None,
        }
    }
}


