/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppPipelineEventStepLevel : Used to distinguish between pipelines, stages, jobs and steps.

/// Used to distinguish between pipelines, stages, jobs and steps.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CiAppPipelineEventStepLevel {
    #[serde(rename = "step")]
    STEP,

}

impl ToString for CiAppPipelineEventStepLevel {
    fn to_string(&self) -> String {
        match self {
            Self::STEP => String::from("step"),
        }
    }
}

impl Default for CiAppPipelineEventStepLevel {
    fn default() -> CiAppPipelineEventStepLevel {
        Self::STEP
    }
}




