/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppPipelineEventStage : Details of a CI stage.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppPipelineEventStage {
    /// A list of stage IDs that this stage depends on.
    #[serde(rename = "dependencies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Option<Vec<String>>>,
    /// Time when the stage run finished. The time format must be RFC3339.
    #[serde(rename = "end")]
    pub end: String,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<Box<crate::models::CiAppCiError>>>,
    #[serde(rename = "git", deserialize_with = "Option::deserialize")]
    pub git: Option<Box<crate::models::CiAppGitInfo>>,
    /// UUID for the stage. It has to be unique at least in the pipeline scope.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "level")]
    pub level: crate::models::CiAppPipelineEventStageLevel,
    /// A list of user-defined metrics. The metrics must follow the `key:value` pattern and the value must be numeric.
    #[serde(rename = "metrics", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Option<Vec<String>>>,
    /// The name for the stage.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "node", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub node: Option<Option<Box<crate::models::CiAppHostInfo>>>,
    /// A map of key-value parameters or environment variables that were defined for the pipeline.
    #[serde(rename = "parameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Option<::std::collections::HashMap<String, String>>>,
    /// The parent pipeline name.
    #[serde(rename = "pipeline_name")]
    pub pipeline_name: String,
    /// The parent pipeline UUID.
    #[serde(rename = "pipeline_unique_id")]
    pub pipeline_unique_id: String,
    /// The queue time in milliseconds, if applicable.
    #[serde(rename = "queue_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_time: Option<Option<i64>>,
    /// Time when the stage run started (it should not include any queue time). The time format must be RFC3339.
    #[serde(rename = "start")]
    pub start: String,
    #[serde(rename = "status")]
    pub status: crate::models::CiAppPipelineEventStageStatus,
    /// A list of user-defined tags. The tags must follow the `key:value` pattern.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
}

impl CiAppPipelineEventStage {
    /// Details of a CI stage.
    pub fn new(end: String, git: Option<crate::models::CiAppGitInfo>, id: String, level: crate::models::CiAppPipelineEventStageLevel, name: String, pipeline_name: String, pipeline_unique_id: String, start: String, status: crate::models::CiAppPipelineEventStageStatus) -> CiAppPipelineEventStage {
        CiAppPipelineEventStage {
            dependencies: None,
            end,
            error: None,
            git: if let Some(x) = git {Some(Box::new(x))} else {None},
            id,
            level,
            metrics: None,
            name,
            node: None,
            parameters: None,
            pipeline_name,
            pipeline_unique_id,
            queue_time: None,
            start,
            status,
            tags: None,
        }
    }
}


