/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CiAppAggregateBucketValue : A bucket value, can either be a timeseries or a single value.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CiAppAggregateBucketValue {
}

impl CiAppAggregateBucketValue {
    /// A bucket value, can either be a timeseries or a single value.
    pub fn new() -> CiAppAggregateBucketValue {
        CiAppAggregateBucketValue {
        }
    }
}


