/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudWorkloadSecurityAgentRuleType : The type of the resource. The value should always be `agent_rule`.

/// The type of the resource. The value should always be `agent_rule`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CloudWorkloadSecurityAgentRuleType {
    #[serde(rename = "agent_rule")]
    AGENT_RULE,

}

impl ToString for CloudWorkloadSecurityAgentRuleType {
    fn to_string(&self) -> String {
        match self {
            Self::AGENT_RULE => String::from("agent_rule"),
        }
    }
}

impl Default for CloudWorkloadSecurityAgentRuleType {
    fn default() -> CloudWorkloadSecurityAgentRuleType {
        Self::AGENT_RULE
    }
}




