/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudWorkloadSecurityAgentRuleData : Object for a single Agent rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudWorkloadSecurityAgentRuleData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::CloudWorkloadSecurityAgentRuleAttributes>>,
    /// The ID of the Agent rule.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::CloudWorkloadSecurityAgentRuleType>,
}

impl CloudWorkloadSecurityAgentRuleData {
    /// Object for a single Agent rule.
    pub fn new() -> CloudWorkloadSecurityAgentRuleData {
        CloudWorkloadSecurityAgentRuleData {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


