/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudWorkloadSecurityAgentRuleUpdaterAttributes : The attributes of the user who last updated the Agent rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudWorkloadSecurityAgentRuleUpdaterAttributes {
    /// The handle of the user.
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    /// The name of the user.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl CloudWorkloadSecurityAgentRuleUpdaterAttributes {
    /// The attributes of the user who last updated the Agent rule.
    pub fn new() -> CloudWorkloadSecurityAgentRuleUpdaterAttributes {
        CloudWorkloadSecurityAgentRuleUpdaterAttributes {
            handle: None,
            name: None,
        }
    }
}


