/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudWorkloadSecurityAgentRuleCreateAttributes : Create a new Cloud Workload Security Agent rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudWorkloadSecurityAgentRuleCreateAttributes {
    /// The description of the Agent rule.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether the Agent rule is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// The SECL expression of the Agent rule.
    #[serde(rename = "expression")]
    pub expression: String,
    /// The name of the Agent rule.
    #[serde(rename = "name")]
    pub name: String,
}

impl CloudWorkloadSecurityAgentRuleCreateAttributes {
    /// Create a new Cloud Workload Security Agent rule.
    pub fn new(expression: String, name: String) -> CloudWorkloadSecurityAgentRuleCreateAttributes {
        CloudWorkloadSecurityAgentRuleCreateAttributes {
            description: None,
            enabled: None,
            expression,
            name,
        }
    }
}


