/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudflareAccountUpdateRequest : Payload schema when updating a Cloudflare account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudflareAccountUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CloudflareAccountUpdateRequestData>,
}

impl CloudflareAccountUpdateRequest {
    /// Payload schema when updating a Cloudflare account.
    pub fn new(data: crate::models::CloudflareAccountUpdateRequestData) -> CloudflareAccountUpdateRequest {
        CloudflareAccountUpdateRequest {
            data: Box::new(data),
        }
    }
}


