/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudflareAccountCreateRequestAttributes : Attributes object for creating a Cloudflare account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudflareAccountCreateRequestAttributes {
    /// The API key (or token) for the Cloudflare account.
    #[serde(rename = "api_key")]
    pub api_key: String,
    /// The email associated with the Cloudflare account. If an API key is provided (and not a token), this field is also required.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The name of the Cloudflare account.
    #[serde(rename = "name")]
    pub name: String,
}

impl CloudflareAccountCreateRequestAttributes {
    /// Attributes object for creating a Cloudflare account.
    pub fn new(api_key: String, name: String) -> CloudflareAccountCreateRequestAttributes {
        CloudflareAccountCreateRequestAttributes {
            api_key,
            email: None,
            name,
        }
    }
}


