/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudWorkloadSecurityAgentRuleResponse : Response object that includes an Agent rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudWorkloadSecurityAgentRuleResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::CloudWorkloadSecurityAgentRuleData>>,
}

impl CloudWorkloadSecurityAgentRuleResponse {
    /// Response object that includes an Agent rule.
    pub fn new() -> CloudWorkloadSecurityAgentRuleResponse {
        CloudWorkloadSecurityAgentRuleResponse {
            data: None,
        }
    }
}


