/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudflareAccountUpdateRequestData : Data object for updating a Cloudflare account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudflareAccountUpdateRequestData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::CloudflareAccountUpdateRequestAttributes>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::CloudflareAccountType>,
}

impl CloudflareAccountUpdateRequestData {
    /// Data object for updating a Cloudflare account.
    pub fn new() -> CloudflareAccountUpdateRequestData {
        CloudflareAccountUpdateRequestData {
            attributes: None,
            r#type: None,
        }
    }
}


