/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CloudflareAccountsResponse : The expected response schema when getting Cloudflare accounts.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudflareAccountsResponse {
    /// The JSON:API data schema.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::CloudflareAccountResponseData>>,
}

impl CloudflareAccountsResponse {
    /// The expected response schema when getting Cloudflare accounts.
    pub fn new() -> CloudflareAccountsResponse {
        CloudflareAccountsResponse {
            data: None,
        }
    }
}


