/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ConfluentResourceResponse : Response schema when interacting with a Confluent resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfluentResourceResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::ConfluentResourceResponseData>>,
}

impl ConfluentResourceResponse {
    /// Response schema when interacting with a Confluent resource.
    pub fn new() -> ConfluentResourceResponse {
        ConfluentResourceResponse {
            data: None,
        }
    }
}


