/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ConfluentAccountUpdateRequestData : Data object for updating a Confluent account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfluentAccountUpdateRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::ConfluentAccountUpdateRequestAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::ConfluentAccountType,
}

impl ConfluentAccountUpdateRequestData {
    /// Data object for updating a Confluent account.
    pub fn new(attributes: crate::models::ConfluentAccountUpdateRequestAttributes, r#type: crate::models::ConfluentAccountType) -> ConfluentAccountUpdateRequestData {
        ConfluentAccountUpdateRequestData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


