/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ConfluentAccountResponse : The expected response schema when getting a Confluent account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfluentAccountResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::ConfluentAccountResponseData>>,
}

impl ConfluentAccountResponse {
    /// The expected response schema when getting a Confluent account.
    pub fn new() -> ConfluentAccountResponse {
        ConfluentAccountResponse {
            data: None,
        }
    }
}


