/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ConfluentAccountResponseAttributes : The attributes of a Confluent account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfluentAccountResponseAttributes {
    /// The API key associated with your Confluent account.
    #[serde(rename = "api_key")]
    pub api_key: String,
    /// A list of Confluent resources associated with the Confluent account.
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<crate::models::ConfluentResourceResponseAttributes>>,
    /// A list of strings representing tags. Can be a single key, or key-value pairs separated by a colon.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl ConfluentAccountResponseAttributes {
    /// The attributes of a Confluent account.
    pub fn new(api_key: String) -> ConfluentAccountResponseAttributes {
        ConfluentAccountResponseAttributes {
            api_key,
            resources: None,
            tags: None,
        }
    }
}


