/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ConfluentAccountType : The JSON:API type for this API. Should always be `confluent-cloud-accounts`.

/// The JSON:API type for this API. Should always be `confluent-cloud-accounts`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfluentAccountType {
    #[serde(rename = "confluent-cloud-accounts")]
    CONFLUENT_CLOUD_ACCOUNTS,

}

impl ToString for ConfluentAccountType {
    fn to_string(&self) -> String {
        match self {
            Self::CONFLUENT_CLOUD_ACCOUNTS => String::from("confluent-cloud-accounts"),
        }
    }
}

impl Default for ConfluentAccountType {
    fn default() -> ConfluentAccountType {
        Self::CONFLUENT_CLOUD_ACCOUNTS
    }
}




