/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardListAddItemsResponse : Response containing a list of added dashboards.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DashboardListAddItemsResponse {
    /// List of dashboards added to the dashboard list.
    #[serde(rename = "added_dashboards_to_list", skip_serializing_if = "Option::is_none")]
    pub added_dashboards_to_list: Option<Vec<crate::models::DashboardListItemResponse>>,
}

impl DashboardListAddItemsResponse {
    /// Response containing a list of added dashboards.
    pub fn new() -> DashboardListAddItemsResponse {
        DashboardListAddItemsResponse {
            added_dashboards_to_list: None,
        }
    }
}


