/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardListAddItemsRequest : Request containing a list of dashboards to add.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DashboardListAddItemsRequest {
    /// List of dashboards to add the dashboard list.
    #[serde(rename = "dashboards", skip_serializing_if = "Option::is_none")]
    pub dashboards: Option<Vec<crate::models::DashboardListItemRequest>>,
}

impl DashboardListAddItemsRequest {
    /// Request containing a list of dashboards to add.
    pub fn new() -> DashboardListAddItemsRequest {
        DashboardListAddItemsRequest {
            dashboards: None,
        }
    }
}


