/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardListUpdateItemsRequest : Request containing the list of dashboards to update to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DashboardListUpdateItemsRequest {
    /// List of dashboards to update the dashboard list to.
    #[serde(rename = "dashboards", skip_serializing_if = "Option::is_none")]
    pub dashboards: Option<Vec<crate::models::DashboardListItemRequest>>,
}

impl DashboardListUpdateItemsRequest {
    /// Request containing the list of dashboards to update to.
    pub fn new() -> DashboardListUpdateItemsRequest {
        DashboardListUpdateItemsRequest {
            dashboards: None,
        }
    }
}


