/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DataScalarColumn : A column containing the numerical results for a formula or query.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataScalarColumn {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ScalarMeta>>,
    /// The name referencing the formula or query for this column.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of column present.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The array of numerical values for one formula or query.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f64>>,
}

impl DataScalarColumn {
    /// A column containing the numerical results for a formula or query.
    pub fn new() -> DataScalarColumn {
        DataScalarColumn {
            meta: None,
            name: None,
            r#type: None,
            values: None,
        }
    }
}


