/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DetailedFinding : A single finding with with message and resource configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DetailedFinding {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::DetailedFindingAttributes>>,
    /// The unique ID for this finding.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::DetailedFindingType>,
}

impl DetailedFinding {
    /// A single finding with with message and resource configuration.
    pub fn new() -> DetailedFinding {
        DetailedFinding {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


