/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeScheduleRecurrencesCreateRequest : A recurring downtime schedule definition.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeScheduleRecurrencesCreateRequest {
    /// A list of downtime recurrences.
    #[serde(rename = "recurrences")]
    pub recurrences: Vec<crate::models::DowntimeScheduleRecurrenceCreateUpdateRequest>,
    /// The timezone in which to schedule the downtime.
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl DowntimeScheduleRecurrencesCreateRequest {
    /// A recurring downtime schedule definition.
    pub fn new(recurrences: Vec<crate::models::DowntimeScheduleRecurrenceCreateUpdateRequest>) -> DowntimeScheduleRecurrencesCreateRequest {
        DowntimeScheduleRecurrencesCreateRequest {
            recurrences,
            timezone: None,
        }
    }
}


