/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeMonitorIdentifier : Monitor identifier for the downtime.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeMonitorIdentifier {
    /// ID of the monitor to prevent notifications.
    #[serde(rename = "monitor_id")]
    pub monitor_id: i64,
    /// A list of monitor tags. For example, tags that are applied directly to monitors, not tags that are used in monitor queries (which are filtered by the scope parameter), to which the downtime applies. The resulting downtime applies to monitors that match **all** provided monitor tags. Setting `monitor_tags` to `[*]` configures the downtime to mute all monitors for the given scope.
    #[serde(rename = "monitor_tags")]
    pub monitor_tags: Vec<String>,
}

impl DowntimeMonitorIdentifier {
    /// Monitor identifier for the downtime.
    pub fn new(monitor_id: i64, monitor_tags: Vec<String>) -> DowntimeMonitorIdentifier {
        DowntimeMonitorIdentifier {
            monitor_id,
            monitor_tags,
        }
    }
}


