/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeRelationshipsMonitor : The monitor identified by the downtime.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeRelationshipsMonitor {
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<Box<crate::models::DowntimeRelationshipsMonitorData>>>,
}

impl DowntimeRelationshipsMonitor {
    /// The monitor identified by the downtime.
    pub fn new() -> DowntimeRelationshipsMonitor {
        DowntimeRelationshipsMonitor {
            data: None,
        }
    }
}


