/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeRelationshipsMonitorData : Data for the monitor.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeRelationshipsMonitorData {
    /// Monitor ID of the downtime.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::DowntimeIncludedMonitorType>,
}

impl DowntimeRelationshipsMonitorData {
    /// Data for the monitor.
    pub fn new() -> DowntimeRelationshipsMonitorData {
        DowntimeRelationshipsMonitorData {
            id: None,
            r#type: None,
        }
    }
}


