/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeMetaPage : Object containing the total filtered count.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeMetaPage {
    /// Total count of elements matched by the filter.
    #[serde(rename = "total_filtered_count", skip_serializing_if = "Option::is_none")]
    pub total_filtered_count: Option<i64>,
}

impl DowntimeMetaPage {
    /// Object containing the total filtered count.
    pub fn new() -> DowntimeMetaPage {
        DowntimeMetaPage {
            total_filtered_count: None,
        }
    }
}


