/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeRelationships : All relationships associated with downtime.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeRelationships {
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::DowntimeRelationshipsCreatedBy>>,
    #[serde(rename = "monitor", skip_serializing_if = "Option::is_none")]
    pub monitor: Option<Box<crate::models::DowntimeRelationshipsMonitor>>,
}

impl DowntimeRelationships {
    /// All relationships associated with downtime.
    pub fn new() -> DowntimeRelationships {
        DowntimeRelationships {
            created_by: None,
            monitor: None,
        }
    }
}


