/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeResourceType : Downtime resource type.

/// Downtime resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DowntimeResourceType {
    #[serde(rename = "downtime")]
    DOWNTIME,

}

impl ToString for DowntimeResourceType {
    fn to_string(&self) -> String {
        match self {
            Self::DOWNTIME => String::from("downtime"),
        }
    }
}

impl Default for DowntimeResourceType {
    fn default() -> DowntimeResourceType {
        Self::DOWNTIME
    }
}




