/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DowntimeScheduleOneTimeResponse : A one-time downtime definition.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DowntimeScheduleOneTimeResponse {
    /// ISO-8601 Datetime to end the downtime.
    #[serde(rename = "end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end: Option<Option<String>>,
    /// ISO-8601 Datetime to start the downtime.
    #[serde(rename = "start")]
    pub start: String,
}

impl DowntimeScheduleOneTimeResponse {
    /// A one-time downtime definition.
    pub fn new(start: String) -> DowntimeScheduleOneTimeResponse {
        DowntimeScheduleOneTimeResponse {
            end: None,
            start,
        }
    }
}


