/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventsQueryOptions : The global query options that are used. Either provide a timezone or a time offset but not both, otherwise the query fails.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventsQueryOptions {
    /// The time offset to apply to the query in seconds.
    #[serde(rename = "timeOffset", skip_serializing_if = "Option::is_none")]
    pub time_offset: Option<i64>,
    /// The timezone can be specified as GMT, UTC, an offset from UTC (like UTC+1), or as a Timezone Database identifier (like America/New_York).
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl EventsQueryOptions {
    /// The global query options that are used. Either provide a timezone or a time offset but not both, otherwise the query fails.
    pub fn new() -> EventsQueryOptions {
        EventsQueryOptions {
            time_offset: None,
            timezone: None,
        }
    }
}


