/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventsGroupBySort : The dimension by which to sort a query's results.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventsGroupBySort {
    #[serde(rename = "aggregation")]
    pub aggregation: crate::models::EventsAggregation,
    /// The metric's calculated value which should be used to define the sort order of a query's results.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<crate::models::QuerySortOrder>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::EventsSortType>,
}

impl EventsGroupBySort {
    /// The dimension by which to sort a query's results.
    pub fn new(aggregation: crate::models::EventsAggregation) -> EventsGroupBySort {
        EventsGroupBySort {
            aggregation,
            metric: None,
            order: None,
            r#type: None,
        }
    }
}


