/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventsGroupBy : A dimension on which to split a query's results.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventsGroupBy {
    /// The facet by which to split groups.
    #[serde(rename = "facet")]
    pub facet: String,
    /// The maximum number of groups to return.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<crate::models::EventsGroupBySort>>,
}

impl EventsGroupBy {
    /// A dimension on which to split a query's results.
    pub fn new(facet: String) -> EventsGroupBy {
        EventsGroupBy {
            facet,
            limit: None,
            sort: None,
        }
    }
}


