/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventsSortType : The type of sort to use on the calculated value.

/// The type of sort to use on the calculated value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventsSortType {
    #[serde(rename = "alphabetical")]
    ALPHABETICAL,
    #[serde(rename = "measure")]
    MEASURE,

}

impl ToString for EventsSortType {
    fn to_string(&self) -> String {
        match self {
            Self::ALPHABETICAL => String::from("alphabetical"),
            Self::MEASURE => String::from("measure"),
        }
    }
}

impl Default for EventsSortType {
    fn default() -> EventsSortType {
        Self::ALPHABETICAL
    }
}




