/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventType : Type of the event.

/// Type of the event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "event")]
    EVENT,

}

impl ToString for EventType {
    fn to_string(&self) -> String {
        match self {
            Self::EVENT => String::from("event"),
        }
    }
}

impl Default for EventType {
    fn default() -> EventType {
        Self::EVENT
    }
}




