/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyServiceType : The JSON:API type for this API. Should always be `fastly-services`.

/// The JSON:API type for this API. Should always be `fastly-services`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FastlyServiceType {
    #[serde(rename = "fastly-services")]
    FASTLY_SERVICES,

}

impl ToString for FastlyServiceType {
    fn to_string(&self) -> String {
        match self {
            Self::FASTLY_SERVICES => String::from("fastly-services"),
        }
    }
}

impl Default for FastlyServiceType {
    fn default() -> FastlyServiceType {
        Self::FASTLY_SERVICES
    }
}




