/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyServiceRequest : Payload schema for Fastly service requests.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyServiceRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::FastlyServiceData>,
}

impl FastlyServiceRequest {
    /// Payload schema for Fastly service requests.
    pub fn new(data: crate::models::FastlyServiceData) -> FastlyServiceRequest {
        FastlyServiceRequest {
            data: Box::new(data),
        }
    }
}


