/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyAccountResponse : The expected response schema when getting a Fastly account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyAccountResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::FastlyAccountResponseData>>,
}

impl FastlyAccountResponse {
    /// The expected response schema when getting a Fastly account.
    pub fn new() -> FastlyAccountResponse {
        FastlyAccountResponse {
            data: None,
        }
    }
}


