/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyAccountResponseData : Data object of a Fastly account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyAccountResponseData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::FastlyAccounResponseAttributes>,
    /// The ID of the Fastly account, a hash of the account name.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::FastlyAccountType,
}

impl FastlyAccountResponseData {
    /// Data object of a Fastly account.
    pub fn new(attributes: crate::models::FastlyAccounResponseAttributes, id: String, r#type: crate::models::FastlyAccountType) -> FastlyAccountResponseData {
        FastlyAccountResponseData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}


