/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyAccountCreateRequest : Payload schema when adding a Fastly account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyAccountCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::FastlyAccountCreateRequestData>,
}

impl FastlyAccountCreateRequest {
    /// Payload schema when adding a Fastly account.
    pub fn new(data: crate::models::FastlyAccountCreateRequestData) -> FastlyAccountCreateRequest {
        FastlyAccountCreateRequest {
            data: Box::new(data),
        }
    }
}


