/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyAccounResponseAttributes : Attributes object of a Fastly account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyAccounResponseAttributes {
    /// The name of the Fastly account.
    #[serde(rename = "name")]
    pub name: String,
    /// A list of services belonging to the parent account.
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<crate::models::FastlyService>>,
}

impl FastlyAccounResponseAttributes {
    /// Attributes object of a Fastly account.
    pub fn new(name: String) -> FastlyAccounResponseAttributes {
        FastlyAccounResponseAttributes {
            name,
            services: None,
        }
    }
}


