/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FastlyServiceData : Data object for Fastly service requests.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FastlyServiceData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::FastlyServiceAttributes>>,
    /// The ID of the Fastly service.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::FastlyServiceType,
}

impl FastlyServiceData {
    /// Data object for Fastly service requests.
    pub fn new(id: String, r#type: crate::models::FastlyServiceType) -> FastlyServiceData {
        FastlyServiceData {
            attributes: None,
            id,
            r#type,
        }
    }
}


