/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FindingType : The JSON:API type for findings.

/// The JSON:API type for findings.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FindingType {
    #[serde(rename = "finding")]
    FINDING,

}

impl ToString for FindingType {
    fn to_string(&self) -> String {
        match self {
            Self::FINDING => String::from("finding"),
        }
    }
}

impl Default for FindingType {
    fn default() -> FindingType {
        Self::FINDING
    }
}




