/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FindingRule : The rule that triggered this finding.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FindingRule {
    /// The ID of the rule that triggered this finding.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the rule that triggered this finding.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl FindingRule {
    /// The rule that triggered this finding.
    pub fn new() -> FindingRule {
        FindingRule {
            id: None,
            name: None,
        }
    }
}


