/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GcpServiceAccountType : The type of account.

/// The type of account.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GcpServiceAccountType {
    #[serde(rename = "gcp_service_account")]
    GCP_SERVICE_ACCOUNT,

}

impl ToString for GcpServiceAccountType {
    fn to_string(&self) -> String {
        match self {
            Self::GCP_SERVICE_ACCOUNT => String::from("gcp_service_account"),
        }
    }
}

impl Default for GcpServiceAccountType {
    fn default() -> GcpServiceAccountType {
        Self::GCP_SERVICE_ACCOUNT
    }
}




