/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GcpstsServiceAccountData : Additional metadata on your generated service account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GcpstsServiceAccountData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::GcpstsServiceAccountAttributes>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::GcpServiceAccountType>,
}

impl GcpstsServiceAccountData {
    /// Additional metadata on your generated service account.
    pub fn new() -> GcpstsServiceAccountData {
        GcpstsServiceAccountData {
            attributes: None,
            r#type: None,
        }
    }
}


