/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GcpstsDelegateAccount : Datadog principal service account info.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GcpstsDelegateAccount {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::GcpstsDelegateAccountAttributes>>,
    /// The ID of the delegate service account.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::GcpstsDelegateAccountType>,
}

impl GcpstsDelegateAccount {
    /// Datadog principal service account info.
    pub fn new() -> GcpstsDelegateAccount {
        GcpstsDelegateAccount {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


