/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GcpstsServiceAccountUpdateRequestData : Data on your service account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GcpstsServiceAccountUpdateRequestData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::GcpstsServiceAccountAttributes>>,
    /// Your service account's unique ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::GcpServiceAccountType>,
}

impl GcpstsServiceAccountUpdateRequestData {
    /// Data on your service account.
    pub fn new() -> GcpstsServiceAccountUpdateRequestData {
        GcpstsServiceAccountUpdateRequestData {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


