/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GetTeamMembershipsSort : Specifies the order of returned team memberships

/// Specifies the order of returned team memberships
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GetTeamMembershipsSort {
    #[serde(rename = "manager_name")]
    MANAGER_NAME,
    #[serde(rename = "-manager_name")]
    _MANAGER_NAME,
    #[serde(rename = "name")]
    NAME,
    #[serde(rename = "-name")]
    _NAME,
    #[serde(rename = "handle")]
    HANDLE,
    #[serde(rename = "-handle")]
    _HANDLE,
    #[serde(rename = "email")]
    EMAIL,
    #[serde(rename = "-email")]
    _EMAIL,

}

impl ToString for GetTeamMembershipsSort {
    fn to_string(&self) -> String {
        match self {
            Self::MANAGER_NAME => String::from("manager_name"),
            Self::_MANAGER_NAME => String::from("-manager_name"),
            Self::NAME => String::from("name"),
            Self::_NAME => String::from("-name"),
            Self::HANDLE => String::from("handle"),
            Self::_HANDLE => String::from("-handle"),
            Self::EMAIL => String::from("email"),
            Self::_EMAIL => String::from("-email"),
        }
    }
}

impl Default for GetTeamMembershipsSort {
    fn default() -> GetTeamMembershipsSort {
        Self::MANAGER_NAME
    }
}




