/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// GroupScalarColumn : A column containing the tag keys and values in a group.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupScalarColumn {
    /// The name of the tag key or group.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of column present.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The array of tag values for each group found for the results of the formulas or queries.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<Vec<String>>>,
}

impl GroupScalarColumn {
    /// A column containing the tag keys and values in a group.
    pub fn new() -> GroupScalarColumn {
        GroupScalarColumn {
            name: None,
            r#type: None,
            values: None,
        }
    }
}


