/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HourlyUsageResponse : Hourly usage response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HourlyUsageResponse {
    /// Response containing hourly usage.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::HourlyUsage>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::HourlyUsageMetadata>>,
}

impl HourlyUsageResponse {
    /// Hourly usage response.
    pub fn new() -> HourlyUsageResponse {
        HourlyUsageResponse {
            data: None,
            meta: None,
        }
    }
}


