/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentUpdateRequest : The update request for an incident's attachments.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentAttachmentUpdateRequest {
    /// An array of incident attachments. An attachment object without an \"id\" key indicates that you want to create that attachment. An attachment object without an \"attributes\" key indicates that you want to delete that attachment. An attachment object with both the \"id\" key and a populated \"attributes\" object indicates that you want to update that attachment.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::IncidentAttachmentUpdateData>,
}

impl IncidentAttachmentUpdateRequest {
    /// The update request for an incident's attachments.
    pub fn new(data: Vec<crate::models::IncidentAttachmentUpdateData>) -> IncidentAttachmentUpdateRequest {
        IncidentAttachmentUpdateRequest {
            data,
        }
    }
}


