/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentFieldAttributesValueType : Type of the multiple value field definitions.

/// Type of the multiple value field definitions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentFieldAttributesValueType {
    #[serde(rename = "multiselect")]
    MULTISELECT,
    #[serde(rename = "textarray")]
    TEXTARRAY,
    #[serde(rename = "metrictag")]
    METRICTAG,
    #[serde(rename = "autocomplete")]
    AUTOCOMPLETE,

}

impl ToString for IncidentFieldAttributesValueType {
    fn to_string(&self) -> String {
        match self {
            Self::MULTISELECT => String::from("multiselect"),
            Self::TEXTARRAY => String::from("textarray"),
            Self::METRICTAG => String::from("metrictag"),
            Self::AUTOCOMPLETE => String::from("autocomplete"),
        }
    }
}

impl Default for IncidentFieldAttributesValueType {
    fn default() -> IncidentFieldAttributesValueType {
        Self::MULTISELECT
    }
}




