/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentIntegrationMetadataResponseIncludedItem : An object related to an incident integration metadata that is included in the response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentIntegrationMetadataResponseIncludedItem {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::UserAttributes>>,
    /// ID of the user.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::UserResponseRelationships>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::UsersType>,
}

impl IncidentIntegrationMetadataResponseIncludedItem {
    /// An object related to an incident integration metadata that is included in the response.
    pub fn new() -> IncidentIntegrationMetadataResponseIncludedItem {
        IncidentIntegrationMetadataResponseIncludedItem {
            attributes: None,
            id: None,
            relationships: None,
            r#type: None,
        }
    }
}


