/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTeamRelationships : The incident team's relationships.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTeamRelationships {
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::RelationshipToUser>>,
    #[serde(rename = "last_modified_by", skip_serializing_if = "Option::is_none")]
    pub last_modified_by: Option<Box<crate::models::RelationshipToUser>>,
}

impl IncidentTeamRelationships {
    /// The incident team's relationships.
    pub fn new() -> IncidentTeamRelationships {
        IncidentTeamRelationships {
            created_by: None,
            last_modified_by: None,
        }
    }
}


