/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentSearchResponseUserFacetData : Facet data for user attributes of an incident.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentSearchResponseUserFacetData {
    /// Count of the facet value appearing in search results.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Email of the user.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Handle of the user.
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    /// Name of the user.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID of the user.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl IncidentSearchResponseUserFacetData {
    /// Facet data for user attributes of an incident.
    pub fn new() -> IncidentSearchResponseUserFacetData {
        IncidentSearchResponseUserFacetData {
            count: None,
            email: None,
            handle: None,
            name: None,
            uuid: None,
        }
    }
}


