/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentFieldAttributesSingleValueType : Type of the single value field definitions.

/// Type of the single value field definitions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentFieldAttributesSingleValueType {
    #[serde(rename = "dropdown")]
    DROPDOWN,
    #[serde(rename = "textbox")]
    TEXTBOX,

}

impl ToString for IncidentFieldAttributesSingleValueType {
    fn to_string(&self) -> String {
        match self {
            Self::DROPDOWN => String::from("dropdown"),
            Self::TEXTBOX => String::from("textbox"),
        }
    }
}

impl Default for IncidentFieldAttributesSingleValueType {
    fn default() -> IncidentFieldAttributesSingleValueType {
        Self::DROPDOWN
    }
}




