/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentUpdateData : Incident data for an update request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentUpdateData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IncidentUpdateAttributes>>,
    /// The incident's ID.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::IncidentUpdateRelationships>>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentType,
}

impl IncidentUpdateData {
    /// Incident data for an update request.
    pub fn new(id: String, r#type: crate::models::IncidentType) -> IncidentUpdateData {
        IncidentUpdateData {
            attributes: None,
            id,
            relationships: None,
            r#type,
        }
    }
}


