/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTodoListResponse : Response with a list of incident todos.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTodoListResponse {
    /// An array of incident todos.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::IncidentTodoResponseData>,
    /// Included related resources that the user requested.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::IncidentTodoResponseIncludedItem>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::IncidentResponseMeta>>,
}

impl IncidentTodoListResponse {
    /// Response with a list of incident todos.
    pub fn new(data: Vec<crate::models::IncidentTodoResponseData>) -> IncidentTodoListResponse {
        IncidentTodoListResponse {
            data,
            included: None,
            meta: None,
        }
    }
}


