/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentUpdateRequest : Update request for an incident.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentUpdateData>,
}

impl IncidentUpdateRequest {
    /// Update request for an incident.
    pub fn new(data: crate::models::IncidentUpdateData) -> IncidentUpdateRequest {
        IncidentUpdateRequest {
            data: Box::new(data),
        }
    }
}


