/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentPostmortemAttachmentType : The type of postmortem attachment attributes.

/// The type of postmortem attachment attributes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentAttachmentPostmortemAttachmentType {
    #[serde(rename = "postmortem")]
    POSTMORTEM,

}

impl ToString for IncidentAttachmentPostmortemAttachmentType {
    fn to_string(&self) -> String {
        match self {
            Self::POSTMORTEM => String::from("postmortem"),
        }
    }
}

impl Default for IncidentAttachmentPostmortemAttachmentType {
    fn default() -> IncidentAttachmentPostmortemAttachmentType {
        Self::POSTMORTEM
    }
}




