/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentFieldAttributes : Dynamic fields for which selections can be made, with field names as keys.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentFieldAttributes {
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentFieldAttributesValueType,
    /// The multiple values selected for this field.
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<Vec<String>>>,
}

impl IncidentFieldAttributes {
    /// Dynamic fields for which selections can be made, with field names as keys.
    pub fn new(r#type: crate::models::IncidentFieldAttributesValueType) -> IncidentFieldAttributes {
        IncidentFieldAttributes {
            r#type,
            value: None,
        }
    }
}


