/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentResponseData : Incident data from a response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentResponseData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IncidentResponseAttributes>>,
    /// The incident's ID.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::IncidentResponseRelationships>>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentType,
}

impl IncidentResponseData {
    /// Incident data from a response.
    pub fn new(id: String, r#type: crate::models::IncidentType) -> IncidentResponseData {
        IncidentResponseData {
            attributes: None,
            id,
            relationships: None,
            r#type,
        }
    }
}


