/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTimelineCellMarkdownCreateAttributes : Timeline cell data for Markdown timeline cells for a create request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTimelineCellMarkdownCreateAttributes {
    #[serde(rename = "cell_type")]
    pub cell_type: crate::models::IncidentTimelineCellMarkdownContentType,
    #[serde(rename = "content")]
    pub content: Box<crate::models::IncidentTimelineCellMarkdownCreateAttributesContent>,
    /// A flag indicating whether the timeline cell is important and should be highlighted.
    #[serde(rename = "important", skip_serializing_if = "Option::is_none")]
    pub important: Option<bool>,
}

impl IncidentTimelineCellMarkdownCreateAttributes {
    /// Timeline cell data for Markdown timeline cells for a create request.
    pub fn new(cell_type: crate::models::IncidentTimelineCellMarkdownContentType, content: crate::models::IncidentTimelineCellMarkdownCreateAttributesContent) -> IncidentTimelineCellMarkdownCreateAttributes {
        IncidentTimelineCellMarkdownCreateAttributes {
            cell_type,
            content: Box::new(content),
            important: None,
        }
    }
}


