/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentUpdateRelationships : The incident's relationships for an update request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentUpdateRelationships {
    #[serde(rename = "commander_user", skip_serializing_if = "Option::is_none")]
    pub commander_user: Option<Box<crate::models::NullableRelationshipToUser>>,
    #[serde(rename = "integrations", skip_serializing_if = "Option::is_none")]
    pub integrations: Option<Box<crate::models::RelationshipToIncidentIntegrationMetadatas>>,
    #[serde(rename = "postmortem", skip_serializing_if = "Option::is_none")]
    pub postmortem: Option<Box<crate::models::RelationshipToIncidentPostmortem>>,
}

impl IncidentUpdateRelationships {
    /// The incident's relationships for an update request.
    pub fn new() -> IncidentUpdateRelationships {
        IncidentUpdateRelationships {
            commander_user: None,
            integrations: None,
            postmortem: None,
        }
    }
}


