/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentIntegrationMetadataPatchRequest : Patch request for an incident integration metadata.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentIntegrationMetadataPatchRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentIntegrationMetadataPatchData>,
}

impl IncidentIntegrationMetadataPatchRequest {
    /// Patch request for an incident integration metadata.
    pub fn new(data: crate::models::IncidentIntegrationMetadataPatchData) -> IncidentIntegrationMetadataPatchRequest {
        IncidentIntegrationMetadataPatchRequest {
            data: Box::new(data),
        }
    }
}


