/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTodoAnonymousAssignee : Anonymous assignee entity.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTodoAnonymousAssignee {
    /// URL for assignee's icon.
    #[serde(rename = "icon")]
    pub icon: String,
    /// Anonymous assignee's ID.
    #[serde(rename = "id")]
    pub id: String,
    /// Assignee's name.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: crate::models::IncidentTodoAnonymousAssigneeSource,
}

impl IncidentTodoAnonymousAssignee {
    /// Anonymous assignee entity.
    pub fn new(icon: String, id: String, name: String, source: crate::models::IncidentTodoAnonymousAssigneeSource) -> IncidentTodoAnonymousAssignee {
        IncidentTodoAnonymousAssignee {
            icon,
            id,
            name,
            source,
        }
    }
}


