/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTimelineCellMarkdownContentType : Type of the Markdown timeline cell.

/// Type of the Markdown timeline cell.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentTimelineCellMarkdownContentType {
    #[serde(rename = "markdown")]
    MARKDOWN,

}

impl ToString for IncidentTimelineCellMarkdownContentType {
    fn to_string(&self) -> String {
        match self {
            Self::MARKDOWN => String::from("markdown"),
        }
    }
}

impl Default for IncidentTimelineCellMarkdownContentType {
    fn default() -> IncidentTimelineCellMarkdownContentType {
        Self::MARKDOWN
    }
}




