/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentServiceUpdateRequest : Update request with an incident service payload.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentServiceUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentServiceUpdateData>,
}

impl IncidentServiceUpdateRequest {
    /// Update request with an incident service payload.
    pub fn new(data: crate::models::IncidentServiceUpdateData) -> IncidentServiceUpdateRequest {
        IncidentServiceUpdateRequest {
            data: Box::new(data),
        }
    }
}


