/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTodoPatchData : Incident todo data for a patch request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTodoPatchData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::IncidentTodoAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentTodoType,
}

impl IncidentTodoPatchData {
    /// Incident todo data for a patch request.
    pub fn new(attributes: crate::models::IncidentTodoAttributes, r#type: crate::models::IncidentTodoType) -> IncidentTodoPatchData {
        IncidentTodoPatchData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


