/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentData : A single incident attachment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentAttachmentData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::IncidentAttachmentAttributes>,
    /// A unique identifier that represents the incident attachment.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::IncidentAttachmentRelationships>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentAttachmentType,
}

impl IncidentAttachmentData {
    /// A single incident attachment.
    pub fn new(attributes: crate::models::IncidentAttachmentAttributes, id: String, relationships: crate::models::IncidentAttachmentRelationships, r#type: crate::models::IncidentAttachmentType) -> IncidentAttachmentData {
        IncidentAttachmentData {
            attributes: Box::new(attributes),
            id,
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


