/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentType : The incident attachment resource type.

/// The incident attachment resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentAttachmentType {
    #[serde(rename = "incident_attachments")]
    INCIDENT_ATTACHMENTS,

}

impl ToString for IncidentAttachmentType {
    fn to_string(&self) -> String {
        match self {
            Self::INCIDENT_ATTACHMENTS => String::from("incident_attachments"),
        }
    }
}

impl Default for IncidentAttachmentType {
    fn default() -> IncidentAttachmentType {
        Self::INCIDENT_ATTACHMENTS
    }
}




