/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentSearchResponseIncidentsData : Incident returned by the search.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentSearchResponseIncidentsData {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentResponseData>,
}

impl IncidentSearchResponseIncidentsData {
    /// Incident returned by the search.
    pub fn new(data: crate::models::IncidentResponseData) -> IncidentSearchResponseIncidentsData {
        IncidentSearchResponseIncidentsData {
            data: Box::new(data),
        }
    }
}


