/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentSearchResponseFieldFacetData : Facet value and number of occurrences for a property field of an incident.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentSearchResponseFieldFacetData {
    /// Count of the facet value appearing in search results.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The facet value appearing in search results.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl IncidentSearchResponseFieldFacetData {
    /// Facet value and number of occurrences for a property field of an incident.
    pub fn new() -> IncidentSearchResponseFieldFacetData {
        IncidentSearchResponseFieldFacetData {
            count: None,
            name: None,
        }
    }
}


