/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTodoCreateRequest : Create request for an incident todo.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTodoCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentTodoCreateData>,
}

impl IncidentTodoCreateRequest {
    /// Create request for an incident todo.
    pub fn new(data: crate::models::IncidentTodoCreateData) -> IncidentTodoCreateRequest {
        IncidentTodoCreateRequest {
            data: Box::new(data),
        }
    }
}


