/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentIntegrationMetadataPatchData : Incident integration metadata data for a patch request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentIntegrationMetadataPatchData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::IncidentIntegrationMetadataAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentIntegrationMetadataType,
}

impl IncidentIntegrationMetadataPatchData {
    /// Incident integration metadata data for a patch request.
    pub fn new(attributes: crate::models::IncidentIntegrationMetadataAttributes, r#type: crate::models::IncidentIntegrationMetadataType) -> IncidentIntegrationMetadataPatchData {
        IncidentIntegrationMetadataPatchData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


