/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentsResponse : The response object containing an incident's attachments.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentAttachmentsResponse {
    /// An array of incident attachments.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::IncidentAttachmentData>,
    /// Included related resources that the user requested.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::IncidentAttachmentsResponseIncludedItem>>,
}

impl IncidentAttachmentsResponse {
    /// The response object containing an incident's attachments.
    pub fn new(data: Vec<crate::models::IncidentAttachmentData>) -> IncidentAttachmentsResponse {
        IncidentAttachmentsResponse {
            data,
            included: None,
        }
    }
}


