/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentFieldAttributesSingleValue : A field with a single value selected.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentFieldAttributesSingleValue {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::IncidentFieldAttributesSingleValueType>,
    /// The single value selected for this field.
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
}

impl IncidentFieldAttributesSingleValue {
    /// A field with a single value selected.
    pub fn new() -> IncidentFieldAttributesSingleValue {
        IncidentFieldAttributesSingleValue {
            r#type: None,
            value: None,
        }
    }
}


