/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentUpdateAttributes : Incident attachment attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentAttachmentUpdateAttributes {
    #[serde(rename = "attachment")]
    pub attachment: Box<crate::models::IncidentAttachmentLinkAttributesAttachmentObject>,
    #[serde(rename = "attachment_type")]
    pub attachment_type: crate::models::IncidentAttachmentLinkAttachmentType,
}

impl IncidentAttachmentUpdateAttributes {
    /// Incident attachment attributes.
    pub fn new(attachment: crate::models::IncidentAttachmentLinkAttributesAttachmentObject, attachment_type: crate::models::IncidentAttachmentLinkAttachmentType) -> IncidentAttachmentUpdateAttributes {
        IncidentAttachmentUpdateAttributes {
            attachment: Box::new(attachment),
            attachment_type,
        }
    }
}


