/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTodoResponse : Response with an incident todo.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTodoResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::IncidentTodoResponseData>,
    /// Included related resources that the user requested.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::IncidentTodoResponseIncludedItem>>,
}

impl IncidentTodoResponse {
    /// Response with an incident todo.
    pub fn new(data: crate::models::IncidentTodoResponseData) -> IncidentTodoResponse {
        IncidentTodoResponse {
            data: Box::new(data),
            included: None,
        }
    }
}


