/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentCreateRelationships : The relationships the incident will have with other resources once created.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentCreateRelationships {
    #[serde(rename = "commander_user")]
    pub commander_user: Box<crate::models::NullableRelationshipToUser>,
}

impl IncidentCreateRelationships {
    /// The relationships the incident will have with other resources once created.
    pub fn new(commander_user: crate::models::NullableRelationshipToUser) -> IncidentCreateRelationships {
        IncidentCreateRelationships {
            commander_user: Box::new(commander_user),
        }
    }
}


