/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentAttachmentAttributes : The attributes object for an attachment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentAttachmentAttributes {
    #[serde(rename = "attachment")]
    pub attachment: Box<crate::models::IncidentAttachmentLinkAttributesAttachmentObject>,
    #[serde(rename = "attachment_type")]
    pub attachment_type: crate::models::IncidentAttachmentLinkAttachmentType,
}

impl IncidentAttachmentAttributes {
    /// The attributes object for an attachment.
    pub fn new(attachment: crate::models::IncidentAttachmentLinkAttributesAttachmentObject, attachment_type: crate::models::IncidentAttachmentLinkAttachmentType) -> IncidentAttachmentAttributes {
        IncidentAttachmentAttributes {
            attachment: Box::new(attachment),
            attachment_type,
        }
    }
}


