/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentTeamUpdateAttributes : The incident team's attributes for an update request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncidentTeamUpdateAttributes {
    /// Name of the incident team.
    #[serde(rename = "name")]
    pub name: String,
}

impl IncidentTeamUpdateAttributes {
    /// The incident team's attributes for an update request.
    pub fn new(name: String) -> IncidentTeamUpdateAttributes {
        IncidentTeamUpdateAttributes {
            name,
        }
    }
}


