/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IncidentSearchSortOrder : The ways searched incidents can be sorted.

/// The ways searched incidents can be sorted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentSearchSortOrder {
    #[serde(rename = "created")]
    CREATED_ASCENDING,
    #[serde(rename = "-created")]
    CREATED_DESCENDING,

}

impl ToString for IncidentSearchSortOrder {
    fn to_string(&self) -> String {
        match self {
            Self::CREATED_ASCENDING => String::from("created"),
            Self::CREATED_DESCENDING => String::from("-created"),
        }
    }
}

impl Default for IncidentSearchSortOrder {
    fn default() -> IncidentSearchSortOrder {
        Self::CREATED_ASCENDING
    }
}




