/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IntakePayloadAccepted : The payload accepted for intake.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IntakePayloadAccepted {
    /// A list of errors.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
}

impl IntakePayloadAccepted {
    /// The payload accepted for intake.
    pub fn new() -> IntakePayloadAccepted {
        IntakePayloadAccepted {
            errors: None,
        }
    }
}


