/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IpAllowlistResponse : Response containing information about the IP allowlist.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpAllowlistResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::IpAllowlistData>>,
}

impl IpAllowlistResponse {
    /// Response containing information about the IP allowlist.
    pub fn new() -> IpAllowlistResponse {
        IpAllowlistResponse {
            data: None,
        }
    }
}


