/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IpAllowlistData : IP allowlist data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IpAllowlistData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IpAllowlistAttributes>>,
    /// The unique identifier of the org.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::IpAllowlistType,
}

impl IpAllowlistData {
    /// IP allowlist data.
    pub fn new(r#type: crate::models::IpAllowlistType) -> IpAllowlistData {
        IpAllowlistData {
            attributes: None,
            id: None,
            r#type,
        }
    }
}


