/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// JsonapiErrorResponse : API error response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JsonapiErrorResponse {
    /// A list of errors.
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::JsonapiErrorItem>,
}

impl JsonapiErrorResponse {
    /// API error response.
    pub fn new(errors: Vec<crate::models::JsonapiErrorItem>) -> JsonapiErrorResponse {
        JsonapiErrorResponse {
            errors,
        }
    }
}


