/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ListTeamsInclude : Included related resources optionally requested.

/// Included related resources optionally requested.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ListTeamsInclude {
    #[serde(rename = "team_links")]
    TEAM_LINKS,
    #[serde(rename = "user_team_permissions")]
    USER_TEAM_PERMISSIONS,

}

impl ToString for ListTeamsInclude {
    fn to_string(&self) -> String {
        match self {
            Self::TEAM_LINKS => String::from("team_links"),
            Self::USER_TEAM_PERMISSIONS => String::from("user_team_permissions"),
        }
    }
}

impl Default for ListTeamsInclude {
    fn default() -> ListTeamsInclude {
        Self::TEAM_LINKS
    }
}




