/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ListFindingsResponse : The expected response schema when listing findings.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListFindingsResponse {
    /// Array of findings.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Finding>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::ListFindingsMeta>,
}

impl ListFindingsResponse {
    /// The expected response schema when listing findings.
    pub fn new(data: Vec<crate::models::Finding>, meta: crate::models::ListFindingsMeta) -> ListFindingsResponse {
        ListFindingsResponse {
            data,
            meta: Box::new(meta),
        }
    }
}


