/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogType : Type of the event.

/// Type of the event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogType {
    #[serde(rename = "log")]
    LOG,

}

impl ToString for LogType {
    fn to_string(&self) -> String {
        match self {
            Self::LOG => String::from("log"),
        }
    }
}

impl Default for LogType {
    fn default() -> LogType {
        Self::LOG
    }
}




