/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsArchiveOrderDefinitionType : Type of the archive order definition.

/// Type of the archive order definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsArchiveOrderDefinitionType {
    #[serde(rename = "archive_order")]
    ARCHIVE_ORDER,

}

impl ToString for LogsArchiveOrderDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::ARCHIVE_ORDER => String::from("archive_order"),
        }
    }
}

impl Default for LogsArchiveOrderDefinitionType {
    fn default() -> LogsArchiveOrderDefinitionType {
        Self::ARCHIVE_ORDER
    }
}




