/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsStorageTier : Specifies storage type as indexes or online-archives

/// Specifies storage type as indexes or online-archives
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsStorageTier {
    #[serde(rename = "indexes")]
    INDEXES,
    #[serde(rename = "online-archives")]
    ONLINE_ARCHIVES,

}

impl ToString for LogsStorageTier {
    fn to_string(&self) -> String {
        match self {
            Self::INDEXES => String::from("indexes"),
            Self::ONLINE_ARCHIVES => String::from("online-archives"),
        }
    }
}

impl Default for LogsStorageTier {
    fn default() -> LogsStorageTier {
        Self::INDEXES
    }
}




