/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsArchiveCreateRequestDefinition : The definition of an archive.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsArchiveCreateRequestDefinition {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::LogsArchiveCreateRequestAttributes>>,
    /// The type of the resource. The value should always be archives.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl LogsArchiveCreateRequestDefinition {
    /// The definition of an archive.
    pub fn new(r#type: String) -> LogsArchiveCreateRequestDefinition {
        LogsArchiveCreateRequestDefinition {
            attributes: None,
            r#type,
        }
    }
}


