/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsQueryFilter : The search and filter query settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsQueryFilter {
    /// The minimum time for the requested logs, supports date math and regular timestamps (milliseconds).
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// For customers with multiple indexes, the indexes to search. Defaults to ['*'] which means all indexes.
    #[serde(rename = "indexes", skip_serializing_if = "Option::is_none")]
    pub indexes: Option<Vec<String>>,
    /// The search query - following the log search syntax.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "storage_tier", skip_serializing_if = "Option::is_none")]
    pub storage_tier: Option<crate::models::LogsStorageTier>,
    /// The maximum time for the requested logs, supports date math and regular timestamps (milliseconds).
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl LogsQueryFilter {
    /// The search and filter query settings
    pub fn new() -> LogsQueryFilter {
        LogsQueryFilter {
            from: None,
            indexes: None,
            query: None,
            storage_tier: None,
            to: None,
        }
    }
}


