/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsArchiveIntegrationGcs : The GCS archive's integration destination.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsArchiveIntegrationGcs {
    /// A client email.
    #[serde(rename = "client_email")]
    pub client_email: String,
    /// A project ID.
    #[serde(rename = "project_id")]
    pub project_id: String,
}

impl LogsArchiveIntegrationGcs {
    /// The GCS archive's integration destination.
    pub fn new(client_email: String, project_id: String) -> LogsArchiveIntegrationGcs {
        LogsArchiveIntegrationGcs {
            client_email,
            project_id,
        }
    }
}


