/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsAggregateRequestPage : Paging settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsAggregateRequestPage {
    /// The returned paging point to use to get the next results
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl LogsAggregateRequestPage {
    /// Paging settings
    pub fn new() -> LogsAggregateRequestPage {
        LogsAggregateRequestPage {
            cursor: None,
        }
    }
}


