/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsMetricCreateRequest : The new log-based metric body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsMetricCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::LogsMetricCreateData>,
}

impl LogsMetricCreateRequest {
    /// The new log-based metric body.
    pub fn new(data: crate::models::LogsMetricCreateData) -> LogsMetricCreateRequest {
        LogsMetricCreateRequest {
            data: Box::new(data),
        }
    }
}


