/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsAggregateBucketValueTimeseries : A timeseries array



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsAggregateBucketValueTimeseries {
}

impl LogsAggregateBucketValueTimeseries {
    /// A timeseries array
    pub fn new() -> LogsAggregateBucketValueTimeseries {
        LogsAggregateBucketValueTimeseries {
        }
    }
}


