/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsAggregateBucket : A bucket values



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsAggregateBucket {
    /// The key, value pairs for each group by
    #[serde(rename = "by", skip_serializing_if = "Option::is_none")]
    pub by: Option<::std::collections::HashMap<String, serde_json::Value>>,
    /// A map of the metric name -> value for regular compute or list of values for a timeseries
    #[serde(rename = "computes", skip_serializing_if = "Option::is_none")]
    pub computes: Option<::std::collections::HashMap<String, crate::models::LogsAggregateBucketValue>>,
}

impl LogsAggregateBucket {
    /// A bucket values
    pub fn new() -> LogsAggregateBucket {
        LogsAggregateBucket {
            by: None,
            computes: None,
        }
    }
}


