/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsQueryOptions : Global query options that are used during the query. Note: You should only supply timezone or time offset but not both otherwise the query will fail.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsQueryOptions {
    /// The time offset (in seconds) to apply to the query.
    #[serde(rename = "timeOffset", skip_serializing_if = "Option::is_none")]
    pub time_offset: Option<i64>,
    /// The timezone can be specified as GMT, UTC, an offset from UTC (like UTC+1), or as a Timezone Database identifier (like America/New_York).
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl LogsQueryOptions {
    /// Global query options that are used during the query. Note: You should only supply timezone or time offset but not both otherwise the query will fail.
    pub fn new() -> LogsQueryOptions {
        LogsQueryOptions {
            time_offset: None,
            timezone: None,
        }
    }
}


