/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsMetricsResponse : All the available log-based metric objects.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsMetricsResponse {
    /// A list of log-based metric objects.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::LogsMetricResponseData>>,
}

impl LogsMetricsResponse {
    /// All the available log-based metric objects.
    pub fn new() -> LogsMetricsResponse {
        LogsMetricsResponse {
            data: None,
        }
    }
}


