/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricVolumesResponse : Response object which includes a single metric's volume.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricVolumesResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::MetricVolumes>>,
}

impl MetricVolumesResponse {
    /// Response object which includes a single metric's volume.
    pub fn new() -> MetricVolumesResponse {
        MetricVolumesResponse {
            data: None,
        }
    }
}


