/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricBulkConfigureTagsType : The metric bulk configure tags resource.

/// The metric bulk configure tags resource.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricBulkConfigureTagsType {
    #[serde(rename = "metric_bulk_configure_tags")]
    BULK_MANAGE_TAGS,

}

impl ToString for MetricBulkConfigureTagsType {
    fn to_string(&self) -> String {
        match self {
            Self::BULK_MANAGE_TAGS => String::from("metric_bulk_configure_tags"),
        }
    }
}

impl Default for MetricBulkConfigureTagsType {
    fn default() -> MetricBulkConfigureTagsType {
        Self::BULK_MANAGE_TAGS
    }
}




