/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricDistinctVolumeAttributes : Object containing the definition of a metric's distinct volume.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricDistinctVolumeAttributes {
    /// Distinct volume for the given metric.
    #[serde(rename = "distinct_volume", skip_serializing_if = "Option::is_none")]
    pub distinct_volume: Option<i64>,
}

impl MetricDistinctVolumeAttributes {
    /// Object containing the definition of a metric's distinct volume.
    pub fn new() -> MetricDistinctVolumeAttributes {
        MetricDistinctVolumeAttributes {
            distinct_volume: None,
        }
    }
}


