/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricIntakeType : The type of metric. The available types are `0` (unspecified), `1` (count), `2` (rate), and `3` (gauge).

/// The type of metric. The available types are `0` (unspecified), `1` (count), `2` (rate), and `3` (gauge).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricIntakeType {
    #[serde(rename = "0")]
    UNSPECIFIED,
    #[serde(rename = "1")]
    COUNT,
    #[serde(rename = "2")]
    RATE,
    #[serde(rename = "3")]
    GAUGE,

}

impl ToString for MetricIntakeType {
    fn to_string(&self) -> String {
        match self {
            Self::UNSPECIFIED => String::from("0"),
            Self::COUNT => String::from("1"),
            Self::RATE => String::from("2"),
            Self::GAUGE => String::from("3"),
        }
    }
}

impl Default for MetricIntakeType {
    fn default() -> MetricIntakeType {
        Self::UNSPECIFIED
    }
}




