/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricAllTagsAttributes : Object containing the definition of a metric's tags.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricAllTagsAttributes {
    /// List of indexed tag value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl MetricAllTagsAttributes {
    /// Object containing the definition of a metric's tags.
    pub fn new() -> MetricAllTagsAttributes {
        MetricAllTagsAttributes {
            tags: None,
        }
    }
}


