/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfigurationCreateData : Object for a single metric to be configure tags on.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfigurationCreateData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::MetricTagConfigurationCreateAttributes>>,
    /// The metric name for this resource.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::MetricTagConfigurationType,
}

impl MetricTagConfigurationCreateData {
    /// Object for a single metric to be configure tags on.
    pub fn new(id: String, r#type: crate::models::MetricTagConfigurationType) -> MetricTagConfigurationCreateData {
        MetricTagConfigurationCreateData {
            attributes: None,
            id,
            r#type,
        }
    }
}


