/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricActiveConfigurationType : The metric actively queried configuration resource type.

/// The metric actively queried configuration resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricActiveConfigurationType {
    #[serde(rename = "actively_queried_configurations")]
    ACTIVELY_QUERIED_CONFIGURATIONS,

}

impl ToString for MetricActiveConfigurationType {
    fn to_string(&self) -> String {
        match self {
            Self::ACTIVELY_QUERIED_CONFIGURATIONS => String::from("actively_queried_configurations"),
        }
    }
}

impl Default for MetricActiveConfigurationType {
    fn default() -> MetricActiveConfigurationType {
        Self::ACTIVELY_QUERIED_CONFIGURATIONS
    }
}




