/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricSeries : A metric to submit to Datadog. See [Datadog metrics](https://docs.datadoghq.com/developers/metrics/#custom-metrics-properties).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricSeries {
    /// If the type of the metric is rate or count, define the corresponding interval.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i64>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::MetricMetadata>>,
    /// The name of the timeseries.
    #[serde(rename = "metric")]
    pub metric: String,
    /// Points relating to a metric. All points must be objects with timestamp and a scalar value (cannot be a string). Timestamps should be in POSIX time in seconds, and cannot be more than ten minutes in the future or more than one hour in the past.
    #[serde(rename = "points")]
    pub points: Vec<crate::models::MetricPoint>,
    /// A list of resources to associate with this metric.
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<crate::models::MetricResource>>,
    /// The source type name.
    #[serde(rename = "source_type_name", skip_serializing_if = "Option::is_none")]
    pub source_type_name: Option<String>,
    /// A list of tags associated with the metric.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::MetricIntakeType>,
    /// The unit of point value.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl MetricSeries {
    /// A metric to submit to Datadog. See [Datadog metrics](https://docs.datadoghq.com/developers/metrics/#custom-metrics-properties).
    pub fn new(metric: String, points: Vec<crate::models::MetricPoint>) -> MetricSeries {
        MetricSeries {
            interval: None,
            metadata: None,
            metric,
            points,
            resources: None,
            source_type_name: None,
            tags: None,
            r#type: None,
            unit: None,
        }
    }
}


