/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricEstimateAttributes : Object containing the definition of a metric estimate attribute.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricEstimateAttributes {
    #[serde(rename = "estimate_type", skip_serializing_if = "Option::is_none")]
    pub estimate_type: Option<crate::models::MetricEstimateType>,
    /// Timestamp when the cardinality estimate was requested.
    #[serde(rename = "estimated_at", skip_serializing_if = "Option::is_none")]
    pub estimated_at: Option<String>,
    /// Estimated cardinality of the metric based on the queried configuration.
    #[serde(rename = "estimated_output_series", skip_serializing_if = "Option::is_none")]
    pub estimated_output_series: Option<i64>,
}

impl MetricEstimateAttributes {
    /// Object containing the definition of a metric estimate attribute.
    pub fn new() -> MetricEstimateAttributes {
        MetricEstimateAttributes {
            estimate_type: None,
            estimated_at: None,
            estimated_output_series: None,
        }
    }
}


