/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfigurationUpdateData : Object for a single tag configuration to be edited.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfigurationUpdateData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::MetricTagConfigurationUpdateAttributes>>,
    /// The metric name for this resource.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::MetricTagConfigurationType,
}

impl MetricTagConfigurationUpdateData {
    /// Object for a single tag configuration to be edited.
    pub fn new(id: String, r#type: crate::models::MetricTagConfigurationType) -> MetricTagConfigurationUpdateData {
        MetricTagConfigurationUpdateData {
            attributes: None,
            id,
            r#type,
        }
    }
}


