/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfigurationCreateAttributes : Object containing the definition of a metric tag configuration to be created.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfigurationCreateAttributes {
    /// A list of queryable aggregation combinations for a count, rate, or gauge metric. By default, count and rate metrics require the (time: sum, space: sum) aggregation and Gauge metrics require the (time: avg, space: avg) aggregation. Additional time & space combinations are also available:  - time: avg, space: avg - time: avg, space: max - time: avg, space: min - time: avg, space: sum - time: count, space: sum - time: max, space: max - time: min, space: min - time: sum, space: avg - time: sum, space: sum  Can only be applied to metrics that have a `metric_type` of `count`, `rate`, or `gauge`.
    #[serde(rename = "aggregations", skip_serializing_if = "Option::is_none")]
    pub aggregations: Option<Vec<crate::models::MetricCustomAggregation>>,
    /// Toggle to include/exclude percentiles for a distribution metric. Defaults to false. Can only be applied to metrics that have a `metric_type` of `distribution`.
    #[serde(rename = "include_percentiles", skip_serializing_if = "Option::is_none")]
    pub include_percentiles: Option<bool>,
    #[serde(rename = "metric_type")]
    pub metric_type: crate::models::MetricTagConfigurationMetricTypes,
    /// A list of tag keys that will be queryable for your metric.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl MetricTagConfigurationCreateAttributes {
    /// Object containing the definition of a metric tag configuration to be created.
    pub fn new(metric_type: crate::models::MetricTagConfigurationMetricTypes, tags: Vec<String>) -> MetricTagConfigurationCreateAttributes {
        MetricTagConfigurationCreateAttributes {
            aggregations: None,
            include_percentiles: None,
            metric_type,
            tags,
        }
    }
}


