/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricEstimateResourceType : The metric estimate resource type.

/// The metric estimate resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricEstimateResourceType {
    #[serde(rename = "metric_cardinality_estimate")]
    METRIC_CARDINALITY_ESTIMATE,

}

impl ToString for MetricEstimateResourceType {
    fn to_string(&self) -> String {
        match self {
            Self::METRIC_CARDINALITY_ESTIMATE => String::from("metric_cardinality_estimate"),
        }
    }
}

impl Default for MetricEstimateResourceType {
    fn default() -> MetricEstimateResourceType {
        Self::METRIC_CARDINALITY_ESTIMATE
    }
}




