/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricPayload : The metrics' payload.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricPayload {
    /// A list of time series to submit to Datadog.
    #[serde(rename = "series")]
    pub series: Vec<crate::models::MetricSeries>,
}

impl MetricPayload {
    /// The metrics' payload.
    pub fn new(series: Vec<crate::models::MetricSeries>) -> MetricPayload {
        MetricPayload {
            series,
        }
    }
}


