/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricBulkTagConfigDeleteAttributes : Optional parameters for bulk deleting metric tag configurations.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricBulkTagConfigDeleteAttributes {
    /// A list of account emails to notify when the configuration is applied.
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
}

impl MetricBulkTagConfigDeleteAttributes {
    /// Optional parameters for bulk deleting metric tag configurations.
    pub fn new() -> MetricBulkTagConfigDeleteAttributes {
        MetricBulkTagConfigDeleteAttributes {
            emails: None,
        }
    }
}


