/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfigurationUpdateRequest : Request object that includes the metric that you would like to edit the tag configuration on.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfigurationUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::MetricTagConfigurationUpdateData>,
}

impl MetricTagConfigurationUpdateRequest {
    /// Request object that includes the metric that you would like to edit the tag configuration on.
    pub fn new(data: crate::models::MetricTagConfigurationUpdateData) -> MetricTagConfigurationUpdateRequest {
        MetricTagConfigurationUpdateRequest {
            data: Box::new(data),
        }
    }
}


