/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricCustomSpaceAggregation : A space aggregation for use in query.

/// A space aggregation for use in query.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricCustomSpaceAggregation {
    #[serde(rename = "avg")]
    AVG,
    #[serde(rename = "max")]
    MAX,
    #[serde(rename = "min")]
    MIN,
    #[serde(rename = "sum")]
    SUM,

}

impl ToString for MetricCustomSpaceAggregation {
    fn to_string(&self) -> String {
        match self {
            Self::AVG => String::from("avg"),
            Self::MAX => String::from("max"),
            Self::MIN => String::from("min"),
            Self::SUM => String::from("sum"),
        }
    }
}

impl Default for MetricCustomSpaceAggregation {
    fn default() -> MetricCustomSpaceAggregation {
        Self::AVG
    }
}




