/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricIngestedIndexedVolumeType : The metric ingested and indexed volume type.

/// The metric ingested and indexed volume type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricIngestedIndexedVolumeType {
    #[serde(rename = "metric_volumes")]
    METRIC_VOLUMES,

}

impl ToString for MetricIngestedIndexedVolumeType {
    fn to_string(&self) -> String {
        match self {
            Self::METRIC_VOLUMES => String::from("metric_volumes"),
        }
    }
}

impl Default for MetricIngestedIndexedVolumeType {
    fn default() -> MetricIngestedIndexedVolumeType {
        Self::METRIC_VOLUMES
    }
}




