/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricMetadata : Metadata for the metric.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricMetadata {
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Box<crate::models::MetricOrigin>>,
}

impl MetricMetadata {
    /// Metadata for the metric.
    pub fn new() -> MetricMetadata {
        MetricMetadata {
            origin: None,
        }
    }
}


