/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricsAggregator : The type of aggregation that can be performed on metrics-based queries.

/// The type of aggregation that can be performed on metrics-based queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetricsAggregator {
    #[serde(rename = "avg")]
    AVG,
    #[serde(rename = "min")]
    MIN,
    #[serde(rename = "max")]
    MAX,
    #[serde(rename = "sum")]
    SUM,
    #[serde(rename = "last")]
    LAST,
    #[serde(rename = "percentile")]
    PERCENTILE,
    #[serde(rename = "mean")]
    MEAN,
    #[serde(rename = "l2norm")]
    L2NORM,
    #[serde(rename = "area")]
    AREA,

}

impl ToString for MetricsAggregator {
    fn to_string(&self) -> String {
        match self {
            Self::AVG => String::from("avg"),
            Self::MIN => String::from("min"),
            Self::MAX => String::from("max"),
            Self::SUM => String::from("sum"),
            Self::LAST => String::from("last"),
            Self::PERCENTILE => String::from("percentile"),
            Self::MEAN => String::from("mean"),
            Self::L2NORM => String::from("l2norm"),
            Self::AREA => String::from("area"),
        }
    }
}

impl Default for MetricsAggregator {
    fn default() -> MetricsAggregator {
        Self::AVG
    }
}




