/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfigurationCreateRequest : Request object that includes the metric that you would like to configure tags for.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfigurationCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::MetricTagConfigurationCreateData>,
}

impl MetricTagConfigurationCreateRequest {
    /// Request object that includes the metric that you would like to configure tags for.
    pub fn new(data: crate::models::MetricTagConfigurationCreateData) -> MetricTagConfigurationCreateRequest {
        MetricTagConfigurationCreateRequest {
            data: Box::new(data),
        }
    }
}


