/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricSuggestedTagsAndAggregations : Object for a single metric's actively queried tags and aggregations.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricSuggestedTagsAndAggregations {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::MetricSuggestedTagsAttributes>>,
    /// The metric name for this resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::MetricActiveConfigurationType>,
}

impl MetricSuggestedTagsAndAggregations {
    /// Object for a single metric's actively queried tags and aggregations.
    pub fn new() -> MetricSuggestedTagsAndAggregations {
        MetricSuggestedTagsAndAggregations {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


