/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricTagConfiguration : Object for a single metric tag configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricTagConfiguration {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::MetricTagConfigurationAttributes>>,
    /// The metric name for this resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::MetricTagConfigurationType>,
}

impl MetricTagConfiguration {
    /// Object for a single metric tag configuration.
    pub fn new() -> MetricTagConfiguration {
        MetricTagConfiguration {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


