/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricEstimateResponse : Response object that includes metric cardinality estimates.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricEstimateResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::MetricEstimate>>,
}

impl MetricEstimateResponse {
    /// Response object that includes metric cardinality estimates.
    pub fn new() -> MetricEstimateResponse {
        MetricEstimateResponse {
            data: None,
        }
    }
}


