/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyAttributeEditRequest : Policy and policy type for a monitor configuration policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorConfigPolicyAttributeEditRequest {
    #[serde(rename = "policy")]
    pub policy: Box<crate::models::MonitorConfigPolicyPolicy>,
    #[serde(rename = "policy_type")]
    pub policy_type: crate::models::MonitorConfigPolicyType,
}

impl MonitorConfigPolicyAttributeEditRequest {
    /// Policy and policy type for a monitor configuration policy.
    pub fn new(policy: crate::models::MonitorConfigPolicyPolicy, policy_type: crate::models::MonitorConfigPolicyType) -> MonitorConfigPolicyAttributeEditRequest {
        MonitorConfigPolicyAttributeEditRequest {
            policy: Box::new(policy),
            policy_type,
        }
    }
}


