/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyPolicyCreateRequest : Configuration for the policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorConfigPolicyPolicyCreateRequest {
    /// The key of the tag.
    #[serde(rename = "tag_key")]
    pub tag_key: String,
    /// If a tag key is required for monitor creation.
    #[serde(rename = "tag_key_required")]
    pub tag_key_required: bool,
    /// Valid values for the tag.
    #[serde(rename = "valid_tag_values")]
    pub valid_tag_values: Vec<String>,
}

impl MonitorConfigPolicyPolicyCreateRequest {
    /// Configuration for the policy.
    pub fn new(tag_key: String, tag_key_required: bool, valid_tag_values: Vec<String>) -> MonitorConfigPolicyPolicyCreateRequest {
        MonitorConfigPolicyPolicyCreateRequest {
            tag_key,
            tag_key_required,
            valid_tag_values,
        }
    }
}


