/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyResponseData : A monitor configuration policy data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorConfigPolicyResponseData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::MonitorConfigPolicyAttributeResponse>>,
    /// ID of this monitor configuration policy.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::MonitorConfigPolicyResourceType>,
}

impl MonitorConfigPolicyResponseData {
    /// A monitor configuration policy data.
    pub fn new() -> MonitorConfigPolicyResponseData {
        MonitorConfigPolicyResponseData {
            attributes: None,
            id: None,
            r#type: None,
        }
    }
}


