/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyAttributeCreateRequest : Policy and policy type for a monitor configuration policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorConfigPolicyAttributeCreateRequest {
    #[serde(rename = "policy")]
    pub policy: Box<crate::models::MonitorConfigPolicyPolicyCreateRequest>,
    #[serde(rename = "policy_type")]
    pub policy_type: crate::models::MonitorConfigPolicyType,
}

impl MonitorConfigPolicyAttributeCreateRequest {
    /// Policy and policy type for a monitor configuration policy.
    pub fn new(policy: crate::models::MonitorConfigPolicyPolicyCreateRequest, policy_type: crate::models::MonitorConfigPolicyType) -> MonitorConfigPolicyAttributeCreateRequest {
        MonitorConfigPolicyAttributeCreateRequest {
            policy: Box::new(policy),
            policy_type,
        }
    }
}


