/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyResourceType : Monitor configuration policy resource type.

/// Monitor configuration policy resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MonitorConfigPolicyResourceType {
    #[serde(rename = "monitor-config-policy")]
    MONITOR_CONFIG_POLICY,

}

impl ToString for MonitorConfigPolicyResourceType {
    fn to_string(&self) -> String {
        match self {
            Self::MONITOR_CONFIG_POLICY => String::from("monitor-config-policy"),
        }
    }
}

impl Default for MonitorConfigPolicyResourceType {
    fn default() -> MonitorConfigPolicyResourceType {
        Self::MONITOR_CONFIG_POLICY
    }
}




