/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorConfigPolicyTagPolicy : Tag attributes of a monitor configuration policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorConfigPolicyTagPolicy {
    /// The key of the tag.
    #[serde(rename = "tag_key", skip_serializing_if = "Option::is_none")]
    pub tag_key: Option<String>,
    /// If a tag key is required for monitor creation.
    #[serde(rename = "tag_key_required", skip_serializing_if = "Option::is_none")]
    pub tag_key_required: Option<bool>,
    /// Valid values for the tag.
    #[serde(rename = "valid_tag_values", skip_serializing_if = "Option::is_none")]
    pub valid_tag_values: Option<Vec<String>>,
}

impl MonitorConfigPolicyTagPolicy {
    /// Tag attributes of a monitor configuration policy.
    pub fn new() -> MonitorConfigPolicyTagPolicy {
        MonitorConfigPolicyTagPolicy {
            tag_key: None,
            tag_key_required: None,
            valid_tag_values: None,
        }
    }
}


