/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MuteFindingResponseProperties : Information about the mute status of this finding.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MuteFindingResponseProperties {
    /// Additional information about the reason why this finding is muted or unmuted. This attribute will not be included in the response if the description is not provided in the request body. 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The expiration date of the mute or unmute action. If the expiration date is not provided in the request body, this attribute will not be included in the response and the finding will be muted or unmuted indefinitely. 
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<i64>,
    /// Whether this finding is muted or unmuted.
    #[serde(rename = "muted", skip_serializing_if = "Option::is_none")]
    pub muted: Option<bool>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<crate::models::FindingMuteReason>,
}

impl MuteFindingResponseProperties {
    /// Information about the mute status of this finding.
    pub fn new() -> MuteFindingResponseProperties {
        MuteFindingResponseProperties {
            description: None,
            expiration_date: None,
            muted: None,
            reason: None,
        }
    }
}


