/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MuteFindingRequestProperties : Object containing the new mute properties of the finding.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MuteFindingRequestProperties {
    /// Additional information about the reason why this finding is muted or unmuted. This field has a maximum limit of 280 characters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The expiration date of the mute or unmute action (Unix ms). It must be set to a value greater than the current timestamp. If this field is not provided, the finding will be muted or unmuted indefinitely, which is equivalent to setting the expiration date to 9999999999999. 
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<i64>,
    /// Whether this finding is muted or unmuted.
    #[serde(rename = "muted")]
    pub muted: bool,
    #[serde(rename = "reason")]
    pub reason: crate::models::FindingMuteReason,
}

impl MuteFindingRequestProperties {
    /// Object containing the new mute properties of the finding.
    pub fn new(muted: bool, reason: crate::models::FindingMuteReason) -> MuteFindingRequestProperties {
        MuteFindingRequestProperties {
            description: None,
            expiration_date: None,
            muted,
            reason,
        }
    }
}


