/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MuteFindingRequestAttributes : The mute properties to be updated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MuteFindingRequestAttributes {
    #[serde(rename = "mute")]
    pub mute: Box<crate::models::MuteFindingRequestProperties>,
}

impl MuteFindingRequestAttributes {
    /// The mute properties to be updated.
    pub fn new(mute: crate::models::MuteFindingRequestProperties) -> MuteFindingRequestAttributes {
        MuteFindingRequestAttributes {
            mute: Box::new(mute),
        }
    }
}


