/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MuteFindingRequestData : Data object containing the new mute properties of the finding.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MuteFindingRequestData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::MuteFindingRequestAttributes>,
    /// The unique ID for this finding.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::FindingType,
}

impl MuteFindingRequestData {
    /// Data object containing the new mute properties of the finding.
    pub fn new(attributes: crate::models::MuteFindingRequestAttributes, id: String, r#type: crate::models::FindingType) -> MuteFindingRequestData {
        MuteFindingRequestData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}


