/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// NullableRelationshipToUser : Relationship to user.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NullableRelationshipToUser {
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<Box<crate::models::NullableRelationshipToUserData>>,
}

impl NullableRelationshipToUser {
    /// Relationship to user.
    pub fn new(data: Option<crate::models::NullableRelationshipToUserData>) -> NullableRelationshipToUser {
        NullableRelationshipToUser {
            data: if let Some(x) = data {Some(Box::new(x))} else {None},
        }
    }
}


