/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OnDemandConcurrencyCapResponse : On-demand concurrency cap response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnDemandConcurrencyCapResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::OnDemandConcurrencyCap>>,
}

impl OnDemandConcurrencyCapResponse {
    /// On-demand concurrency cap response.
    pub fn new() -> OnDemandConcurrencyCapResponse {
        OnDemandConcurrencyCapResponse {
            data: None,
        }
    }
}


