/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OpsgenieServiceResponse : Response of an Opsgenie service.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpsgenieServiceResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::OpsgenieServiceResponseData>,
}

impl OpsgenieServiceResponse {
    /// Response of an Opsgenie service.
    pub fn new(data: crate::models::OpsgenieServiceResponseData) -> OpsgenieServiceResponse {
        OpsgenieServiceResponse {
            data: Box::new(data),
        }
    }
}


