/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OpsgenieServiceUpdateData : Opsgenie service for an update request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpsgenieServiceUpdateData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::OpsgenieServiceUpdateAttributes>,
    /// The ID of the Opsgenie service.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::OpsgenieServiceType,
}

impl OpsgenieServiceUpdateData {
    /// Opsgenie service for an update request.
    pub fn new(attributes: crate::models::OpsgenieServiceUpdateAttributes, id: String, r#type: crate::models::OpsgenieServiceType) -> OpsgenieServiceUpdateData {
        OpsgenieServiceUpdateData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}


