/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OpsgenieServiceCreateAttributes : The Opsgenie service attributes for a create request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpsgenieServiceCreateAttributes {
    /// The custom URL for a custom region.
    #[serde(rename = "custom_url", skip_serializing_if = "Option::is_none")]
    pub custom_url: Option<String>,
    /// The name for the Opsgenie service.
    #[serde(rename = "name")]
    pub name: String,
    /// The Opsgenie API key for your Opsgenie service.
    #[serde(rename = "opsgenie_api_key")]
    pub opsgenie_api_key: String,
    #[serde(rename = "region")]
    pub region: crate::models::OpsgenieServiceRegionType,
}

impl OpsgenieServiceCreateAttributes {
    /// The Opsgenie service attributes for a create request.
    pub fn new(name: String, opsgenie_api_key: String, region: crate::models::OpsgenieServiceRegionType) -> OpsgenieServiceCreateAttributes {
        OpsgenieServiceCreateAttributes {
            custom_url: None,
            name,
            opsgenie_api_key,
            region,
        }
    }
}


