/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OpsgenieServicesResponse : Response with a list of Opsgenie services.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpsgenieServicesResponse {
    /// An array of Opsgenie services.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::OpsgenieServiceResponseData>,
}

impl OpsgenieServicesResponse {
    /// Response with a list of Opsgenie services.
    pub fn new(data: Vec<crate::models::OpsgenieServiceResponseData>) -> OpsgenieServicesResponse {
        OpsgenieServicesResponse {
            data,
        }
    }
}


