/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// Organization : Organization object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Organization {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::OrganizationAttributes>>,
    /// ID of the organization.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::OrganizationsType,
}

impl Organization {
    /// Organization object.
    pub fn new(r#type: crate::models::OrganizationsType) -> Organization {
        Organization {
            attributes: None,
            id: None,
            r#type,
        }
    }
}


