/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationAttributes : Attributes of the organization.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganizationAttributes {
    /// Creation time of the organization.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Description of the organization.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether or not the organization is disabled.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Time of last organization modification.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    /// Name of the organization.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Public ID of the organization.
    #[serde(rename = "public_id", skip_serializing_if = "Option::is_none")]
    pub public_id: Option<String>,
    /// Sharing type of the organization.
    #[serde(rename = "sharing", skip_serializing_if = "Option::is_none")]
    pub sharing: Option<String>,
    /// URL of the site that this organization exists at.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl OrganizationAttributes {
    /// Attributes of the organization.
    pub fn new() -> OrganizationAttributes {
        OrganizationAttributes {
            created_at: None,
            description: None,
            disabled: None,
            modified_at: None,
            name: None,
            public_id: None,
            sharing: None,
            url: None,
        }
    }
}


