/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToIncidentIntegrationMetadatas : A relationship reference for multiple integration metadata objects.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToIncidentIntegrationMetadatas {
    /// Integration metadata relationship array
    #[serde(rename = "data")]
    pub data: Vec<crate::models::RelationshipToIncidentIntegrationMetadataData>,
}

impl RelationshipToIncidentIntegrationMetadatas {
    /// A relationship reference for multiple integration metadata objects.
    pub fn new(data: Vec<crate::models::RelationshipToIncidentIntegrationMetadataData>) -> RelationshipToIncidentIntegrationMetadatas {
        RelationshipToIncidentIntegrationMetadatas {
            data,
        }
    }
}


