/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToIncidentAttachmentData : The attachment relationship data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToIncidentAttachmentData {
    /// A unique identifier that represents the attachment.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::IncidentAttachmentType,
}

impl RelationshipToIncidentAttachmentData {
    /// The attachment relationship data.
    pub fn new(id: String, r#type: crate::models::IncidentAttachmentType) -> RelationshipToIncidentAttachmentData {
        RelationshipToIncidentAttachmentData {
            id,
            r#type,
        }
    }
}


