/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToSamlAssertionAttributeData : Data of AuthN Mapping relationship to SAML Assertion Attribute.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToSamlAssertionAttributeData {
    /// The ID of the SAML assertion attribute.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::SamlAssertionAttributesType,
}

impl RelationshipToSamlAssertionAttributeData {
    /// Data of AuthN Mapping relationship to SAML Assertion Attribute.
    pub fn new(id: String, r#type: crate::models::SamlAssertionAttributesType) -> RelationshipToSamlAssertionAttributeData {
        RelationshipToSamlAssertionAttributeData {
            id,
            r#type,
        }
    }
}


