/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToPermissionData : Relationship to permission object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToPermissionData {
    /// ID of the permission.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::PermissionsType>,
}

impl RelationshipToPermissionData {
    /// Relationship to permission object.
    pub fn new() -> RelationshipToPermissionData {
        RelationshipToPermissionData {
            id: None,
            r#type: None,
        }
    }
}


