/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToUserTeamUser : Relationship between team membership and user



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToUserTeamUser {
    #[serde(rename = "data")]
    pub data: Box<crate::models::RelationshipToUserTeamUserData>,
}

impl RelationshipToUserTeamUser {
    /// Relationship between team membership and user
    pub fn new(data: crate::models::RelationshipToUserTeamUserData) -> RelationshipToUserTeamUser {
        RelationshipToUserTeamUser {
            data: Box::new(data),
        }
    }
}


