/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToRoles : Relationship to roles.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToRoles {
    /// An array containing type and the unique identifier of a role.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::RelationshipToRoleData>>,
}

impl RelationshipToRoles {
    /// Relationship to roles.
    pub fn new() -> RelationshipToRoles {
        RelationshipToRoles {
            data: None,
        }
    }
}


