/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToUserTeamPermission : Relationship between a user team permission and a team



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToUserTeamPermission {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::RelationshipToUserTeamPermissionData>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::TeamRelationshipsLinks>>,
}

impl RelationshipToUserTeamPermission {
    /// Relationship between a user team permission and a team
    pub fn new() -> RelationshipToUserTeamPermission {
        RelationshipToUserTeamPermission {
            data: None,
            links: None,
        }
    }
}


