/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToUserTeamUserData : A user's relationship with a team



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToUserTeamUserData {
    /// The ID of the user associated with the team
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::UserTeamUserType,
}

impl RelationshipToUserTeamUserData {
    /// A user's relationship with a team
    pub fn new(id: String, r#type: crate::models::UserTeamUserType) -> RelationshipToUserTeamUserData {
        RelationshipToUserTeamUserData {
            id,
            r#type,
        }
    }
}


