/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToIncidentAttachment : A relationship reference for attachments.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToIncidentAttachment {
    /// An array of incident attachments.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::RelationshipToIncidentAttachmentData>,
}

impl RelationshipToIncidentAttachment {
    /// A relationship reference for attachments.
    pub fn new(data: Vec<crate::models::RelationshipToIncidentAttachmentData>) -> RelationshipToIncidentAttachment {
        RelationshipToIncidentAttachment {
            data,
        }
    }
}


