/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToOrganizationData : Relationship to organization object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToOrganizationData {
    /// ID of the organization.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::OrganizationsType,
}

impl RelationshipToOrganizationData {
    /// Relationship to organization object.
    pub fn new(id: String, r#type: crate::models::OrganizationsType) -> RelationshipToOrganizationData {
        RelationshipToOrganizationData {
            id,
            r#type,
        }
    }
}


