/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToTeamLinkData : Relationship between a link and a team



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToTeamLinkData {
    /// The team link's identifier
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::TeamLinkType,
}

impl RelationshipToTeamLinkData {
    /// Relationship between a link and a team
    pub fn new(id: String, r#type: crate::models::TeamLinkType) -> RelationshipToTeamLinkData {
        RelationshipToTeamLinkData {
            id,
            r#type,
        }
    }
}


