/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToRole : Relationship to role.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToRole {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::RelationshipToRoleData>>,
}

impl RelationshipToRole {
    /// Relationship to role.
    pub fn new() -> RelationshipToRole {
        RelationshipToRole {
            data: None,
        }
    }
}


