/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RelationshipToUserTeamPermissionData : Related user team permission data



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipToUserTeamPermissionData {
    /// The ID of the user team permission
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::UserTeamPermissionType,
}

impl RelationshipToUserTeamPermissionData {
    /// Related user team permission data
    pub fn new(id: String, r#type: crate::models::UserTeamPermissionType) -> RelationshipToUserTeamPermissionData {
        RelationshipToUserTeamPermissionData {
            id,
            r#type,
        }
    }
}


