/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionPolicyType : Restriction policy type.

/// Restriction policy type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RestrictionPolicyType {
    #[serde(rename = "restriction_policy")]
    RESTRICTION_POLICY,

}

impl ToString for RestrictionPolicyType {
    fn to_string(&self) -> String {
        match self {
            Self::RESTRICTION_POLICY => String::from("restriction_policy"),
        }
    }
}

impl Default for RestrictionPolicyType {
    fn default() -> RestrictionPolicyType {
        Self::RESTRICTION_POLICY
    }
}




