/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionPolicyUpdateRequest : Update request for a restriction policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionPolicyUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::RestrictionPolicy>,
}

impl RestrictionPolicyUpdateRequest {
    /// Update request for a restriction policy.
    pub fn new(data: crate::models::RestrictionPolicy) -> RestrictionPolicyUpdateRequest {
        RestrictionPolicyUpdateRequest {
            data: Box::new(data),
        }
    }
}


