/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionQueryRoleAttribute : Attributes of the role for a restriction query.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionQueryRoleAttribute {
    /// The role name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl RestrictionQueryRoleAttribute {
    /// Attributes of the role for a restriction query.
    pub fn new() -> RestrictionQueryRoleAttribute {
        RestrictionQueryRoleAttribute {
            name: None,
        }
    }
}


