/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionPolicyBinding : Specifies which principals are associated with a relation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionPolicyBinding {
    /// An array of principals. A principal is a subject or group of subjects. Each principal is formatted as `type:id`. Supported types: `role`, `team` (beta), `user` (beta), and `org`. The org ID can be obtained through the api/v2/current_user API. The user principal type accepts service account IDs.
    #[serde(rename = "principals")]
    pub principals: Vec<String>,
    /// The role/level of access.
    #[serde(rename = "relation")]
    pub relation: String,
}

impl RestrictionPolicyBinding {
    /// Specifies which principals are associated with a relation.
    pub fn new(principals: Vec<String>, relation: String) -> RestrictionPolicyBinding {
        RestrictionPolicyBinding {
            principals,
            relation,
        }
    }
}


