/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionPolicyResponse : Response containing information about a single restriction policy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionPolicyResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::RestrictionPolicy>,
}

impl RestrictionPolicyResponse {
    /// Response containing information about a single restriction policy.
    pub fn new(data: crate::models::RestrictionPolicy) -> RestrictionPolicyResponse {
        RestrictionPolicyResponse {
            data: Box::new(data),
        }
    }
}


