/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionQueryWithRelationshipsResponse : Response containing information about a single restriction query.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionQueryWithRelationshipsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::RestrictionQueryWithRelationships>>,
    /// Array of objects related to the restriction query.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<crate::models::RestrictionQueryResponseIncludedItem>>,
}

impl RestrictionQueryWithRelationshipsResponse {
    /// Response containing information about a single restriction query.
    pub fn new() -> RestrictionQueryWithRelationshipsResponse {
        RestrictionQueryWithRelationshipsResponse {
            data: None,
            included: None,
        }
    }
}


