/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionQueryListResponse : Response containing information about multiple restriction queries.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionQueryListResponse {
    /// Array of returned restriction queries.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::RestrictionQueryWithoutRelationships>>,
}

impl RestrictionQueryListResponse {
    /// Response containing information about multiple restriction queries.
    pub fn new() -> RestrictionQueryListResponse {
        RestrictionQueryListResponse {
            data: None,
        }
    }
}


