/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionQueryWithRelationships : Restriction query object returned by the API.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RestrictionQueryWithRelationships {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::RestrictionQueryAttributes>>,
    /// ID of the restriction query.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::RestrictionQueryRelationships>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::LogsRestrictionQueriesType>,
}

impl RestrictionQueryWithRelationships {
    /// Restriction query object returned by the API.
    pub fn new() -> RestrictionQueryWithRelationships {
        RestrictionQueryWithRelationships {
            attributes: None,
            id: None,
            relationships: None,
            r#type: None,
        }
    }
}


