/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RoleCreateResponse : Response containing information about a created role.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleCreateResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::RoleCreateResponseData>>,
}

impl RoleCreateResponse {
    /// Response containing information about a created role.
    pub fn new() -> RoleCreateResponse {
        RoleCreateResponse {
            data: None,
        }
    }
}


