/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RoleCreateAttributes : Attributes of the created role.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleCreateAttributes {
    /// Creation time of the role.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time of last role modification.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    /// Name of the role.
    #[serde(rename = "name")]
    pub name: String,
}

impl RoleCreateAttributes {
    /// Attributes of the created role.
    pub fn new(name: String) -> RoleCreateAttributes {
        RoleCreateAttributes {
            created_at: None,
            modified_at: None,
            name,
        }
    }
}


