/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RoleCreateRequest : Create a role.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::RoleCreateData>,
}

impl RoleCreateRequest {
    /// Create a role.
    pub fn new(data: crate::models::RoleCreateData) -> RoleCreateRequest {
        RoleCreateRequest {
            data: Box::new(data),
        }
    }
}


