/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RoleClone : Data for the clone role request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleClone {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::RoleCloneAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::RolesType,
}

impl RoleClone {
    /// Data for the clone role request.
    pub fn new(attributes: crate::models::RoleCloneAttributes, r#type: crate::models::RolesType) -> RoleClone {
        RoleClone {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


