/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RoleUpdateResponse : Response containing information about an updated role.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleUpdateResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::RoleUpdateResponseData>>,
}

impl RoleUpdateResponse {
    /// Response containing information about an updated role.
    pub fn new() -> RoleUpdateResponse {
        RoleUpdateResponse {
            data: None,
        }
    }
}


