/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RolesSort : Sorting options for roles.

/// Sorting options for roles.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RolesSort {
    #[serde(rename = "name")]
    NAME_ASCENDING,
    #[serde(rename = "-name")]
    NAME_DESCENDING,
    #[serde(rename = "modified_at")]
    MODIFIED_AT_ASCENDING,
    #[serde(rename = "-modified_at")]
    MODIFIED_AT_DESCENDING,
    #[serde(rename = "user_count")]
    USER_COUNT_ASCENDING,
    #[serde(rename = "-user_count")]
    USER_COUNT_DESCENDING,

}

impl ToString for RolesSort {
    fn to_string(&self) -> String {
        match self {
            Self::NAME_ASCENDING => String::from("name"),
            Self::NAME_DESCENDING => String::from("-name"),
            Self::MODIFIED_AT_ASCENDING => String::from("modified_at"),
            Self::MODIFIED_AT_DESCENDING => String::from("-modified_at"),
            Self::USER_COUNT_ASCENDING => String::from("user_count"),
            Self::USER_COUNT_DESCENDING => String::from("-user_count"),
        }
    }
}

impl Default for RolesSort {
    fn default() -> RolesSort {
        Self::NAME_ASCENDING
    }
}




