/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumAggregateBucketValueTimeseries : A timeseries array.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RumAggregateBucketValueTimeseries {
}

impl RumAggregateBucketValueTimeseries {
    /// A timeseries array.
    pub fn new() -> RumAggregateBucketValueTimeseries {
        RumAggregateBucketValueTimeseries {
        }
    }
}


