/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumApplicationListAttributes : RUM application list attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RumApplicationListAttributes {
    /// ID of the RUM application.
    #[serde(rename = "application_id")]
    pub application_id: String,
    /// Timestamp in ms of the creation date.
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Handle of the creator user.
    #[serde(rename = "created_by_handle")]
    pub created_by_handle: String,
    /// Hash of the RUM application. Optional.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Indicates if the RUM application is active.
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Name of the RUM application.
    #[serde(rename = "name")]
    pub name: String,
    /// Org ID of the RUM application.
    #[serde(rename = "org_id")]
    pub org_id: i32,
    /// Type of the RUM application. Supported values are `browser`, `ios`, `android`, `react-native`, `flutter`.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Timestamp in ms of the last update date.
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
    /// Handle of the updater user.
    #[serde(rename = "updated_by_handle")]
    pub updated_by_handle: String,
}

impl RumApplicationListAttributes {
    /// RUM application list attributes.
    pub fn new(application_id: String, created_at: i64, created_by_handle: String, name: String, org_id: i32, r#type: String, updated_at: i64, updated_by_handle: String) -> RumApplicationListAttributes {
        RumApplicationListAttributes {
            application_id,
            created_at,
            created_by_handle,
            hash: None,
            is_active: None,
            name,
            org_id,
            r#type,
            updated_at,
            updated_by_handle,
        }
    }
}


