/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumEventType : Type of the event.

/// Type of the event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RumEventType {
    #[serde(rename = "rum")]
    RUM,

}

impl ToString for RumEventType {
    fn to_string(&self) -> String {
        match self {
            Self::RUM => String::from("rum"),
        }
    }
}

impl Default for RumEventType {
    fn default() -> RumEventType {
        Self::RUM
    }
}




