/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumApplicationType : RUM application response type.

/// RUM application response type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RumApplicationType {
    #[serde(rename = "rum_application")]
    RUM_APPLICATION,

}

impl ToString for RumApplicationType {
    fn to_string(&self) -> String {
        match self {
            Self::RUM_APPLICATION => String::from("rum_application"),
        }
    }
}

impl Default for RumApplicationType {
    fn default() -> RumApplicationType {
        Self::RUM_APPLICATION
    }
}




