/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumSearchEventsRequest : The request for a RUM events list.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RumSearchEventsRequest {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::RumQueryFilter>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::RumQueryOptions>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<crate::models::RumQueryPageOptions>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<crate::models::RumSort>,
}

impl RumSearchEventsRequest {
    /// The request for a RUM events list.
    pub fn new() -> RumSearchEventsRequest {
        RumSearchEventsRequest {
            filter: None,
            options: None,
            page: None,
            sort: None,
        }
    }
}


