/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// RumApplicationsResponse : RUM applications response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RumApplicationsResponse {
    /// RUM applications array response.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::RumApplicationList>>,
}

impl RumApplicationsResponse {
    /// RUM applications response.
    pub fn new() -> RumApplicationsResponse {
        RumApplicationsResponse {
            data: None,
        }
    }
}


