/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SamlAssertionAttributesType : SAML assertion attributes resource type.

/// SAML assertion attributes resource type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SamlAssertionAttributesType {
    #[serde(rename = "saml_assertion_attributes")]
    SAML_ASSERTION_ATTRIBUTES,

}

impl ToString for SamlAssertionAttributesType {
    fn to_string(&self) -> String {
        match self {
            Self::SAML_ASSERTION_ATTRIBUTES => String::from("saml_assertion_attributes"),
        }
    }
}

impl Default for SamlAssertionAttributesType {
    fn default() -> SamlAssertionAttributesType {
        Self::SAML_ASSERTION_ATTRIBUTES
    }
}




