/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ScalarFormulaQueryResponse : A message containing one or more responses to scalar queries.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalarFormulaQueryResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::ScalarResponse>>,
    /// An error generated when processing a request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<String>,
}

impl ScalarFormulaQueryResponse {
    /// A message containing one or more responses to scalar queries.
    pub fn new() -> ScalarFormulaQueryResponse {
        ScalarFormulaQueryResponse {
            data: None,
            errors: None,
        }
    }
}


