/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ScalarMeta : Metadata for the resulting numerical values.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScalarMeta {
    /// Detailed information about the unit. First element describes the \"primary unit\" (for example, `bytes` in `bytes per second`). The second element describes the \"per unit\" (for example, `second` in `bytes per second`). If the second element is not present, the API returns null.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Vec<crate::models::Unit>>,
}

impl ScalarMeta {
    /// Metadata for the resulting numerical values.
    pub fn new() -> ScalarMeta {
        ScalarMeta {
            unit: None,
        }
    }
}


