/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityFilterUpdateAttributes : The security filters properties to be updated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityFilterUpdateAttributes {
    /// Exclusion filters to exclude some logs from the security filter.
    #[serde(rename = "exclusion_filters", skip_serializing_if = "Option::is_none")]
    pub exclusion_filters: Option<Vec<crate::models::SecurityFilterExclusionFilter>>,
    #[serde(rename = "filtered_data_type", skip_serializing_if = "Option::is_none")]
    pub filtered_data_type: Option<crate::models::SecurityFilterFilteredDataType>,
    /// Whether the security filter is enabled.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// The name of the security filter.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The query of the security filter.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// The version of the security filter to update.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl SecurityFilterUpdateAttributes {
    /// The security filters properties to be updated.
    pub fn new() -> SecurityFilterUpdateAttributes {
        SecurityFilterUpdateAttributes {
            exclusion_filters: None,
            filtered_data_type: None,
            is_enabled: None,
            name: None,
            query: None,
            version: None,
        }
    }
}


