/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityFilterUpdateRequest : The new security filter body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityFilterUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SecurityFilterUpdateData>,
}

impl SecurityFilterUpdateRequest {
    /// The new security filter body.
    pub fn new(data: crate::models::SecurityFilterUpdateData) -> SecurityFilterUpdateRequest {
        SecurityFilterUpdateRequest {
            data: Box::new(data),
        }
    }
}


