/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalStateUpdateRequest : Request body for changing the state of a given security monitoring signal.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalStateUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SecurityMonitoringSignalStateUpdateData>,
}

impl SecurityMonitoringSignalStateUpdateRequest {
    /// Request body for changing the state of a given security monitoring signal.
    pub fn new(data: crate::models::SecurityMonitoringSignalStateUpdateData) -> SecurityMonitoringSignalStateUpdateRequest {
        SecurityMonitoringSignalStateUpdateRequest {
            data: Box::new(data),
        }
    }
}


