/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleTypeCreate : The rule type.

/// The rule type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleTypeCreate {
    #[serde(rename = "log_detection")]
    LOG_DETECTION,
    #[serde(rename = "workload_security")]
    WORKLOAD_SECURITY,

}

impl ToString for SecurityMonitoringRuleTypeCreate {
    fn to_string(&self) -> String {
        match self {
            Self::LOG_DETECTION => String::from("log_detection"),
            Self::WORKLOAD_SECURITY => String::from("workload_security"),
        }
    }
}

impl Default for SecurityMonitoringRuleTypeCreate {
    fn default() -> SecurityMonitoringRuleTypeCreate {
        Self::LOG_DETECTION
    }
}




