/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityFilterCreateRequest : Request object that includes the security filter that you would like to create.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityFilterCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SecurityFilterCreateData>,
}

impl SecurityFilterCreateRequest {
    /// Request object that includes the security filter that you would like to create.
    pub fn new(data: crate::models::SecurityFilterCreateData) -> SecurityFilterCreateRequest {
        SecurityFilterCreateRequest {
            data: Box::new(data),
        }
    }
}


