/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityFilterUpdateData : The new security filter properties.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityFilterUpdateData {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::SecurityFilterUpdateAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::SecurityFilterType,
}

impl SecurityFilterUpdateData {
    /// The new security filter properties.
    pub fn new(attributes: crate::models::SecurityFilterUpdateAttributes, r#type: crate::models::SecurityFilterType) -> SecurityFilterUpdateData {
        SecurityFilterUpdateData {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


