/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalAttributes : The object containing all signal attributes and their associated values.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalAttributes {
    /// A JSON object of attributes in the security signal.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<::std::collections::HashMap<String, serde_json::Value>>,
    /// The message in the security signal defined by the rule that generated the signal.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// An array of tags associated with the security signal.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// The timestamp of the security signal.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl SecurityMonitoringSignalAttributes {
    /// The object containing all signal attributes and their associated values.
    pub fn new() -> SecurityMonitoringSignalAttributes {
        SecurityMonitoringSignalAttributes {
            attributes: None,
            message: None,
            tags: None,
            timestamp: None,
        }
    }
}


