/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityFilterAttributes : The object describing a security filter.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityFilterAttributes {
    /// The list of exclusion filters applied in this security filter.
    #[serde(rename = "exclusion_filters", skip_serializing_if = "Option::is_none")]
    pub exclusion_filters: Option<Vec<crate::models::SecurityFilterExclusionFilterResponse>>,
    #[serde(rename = "filtered_data_type", skip_serializing_if = "Option::is_none")]
    pub filtered_data_type: Option<crate::models::SecurityFilterFilteredDataType>,
    /// Whether the security filter is the built-in filter.
    #[serde(rename = "is_builtin", skip_serializing_if = "Option::is_none")]
    pub is_builtin: Option<bool>,
    /// Whether the security filter is enabled.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// The security filter name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The security filter query. Logs accepted by this query will be accepted by this filter.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// The version of the security filter.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl SecurityFilterAttributes {
    /// The object describing a security filter.
    pub fn new() -> SecurityFilterAttributes {
        SecurityFilterAttributes {
            exclusion_filters: None,
            filtered_data_type: None,
            is_builtin: None,
            is_enabled: None,
            name: None,
            query: None,
            version: None,
        }
    }
}


