/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleNewValueOptionsLearningDuration : The duration in days during which values are learned, and after which signals will be generated for values that weren't learned. If set to 0, a signal will be generated for all new values after the first value is learned.

/// The duration in days during which values are learned, and after which signals will be generated for values that weren't learned. If set to 0, a signal will be generated for all new values after the first value is learned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleNewValueOptionsLearningDuration {
    #[serde(rename = "0")]
    ZERO_DAYS,
    #[serde(rename = "1")]
    ONE_DAY,
    #[serde(rename = "7")]
    SEVEN_DAYS,

}

impl ToString for SecurityMonitoringRuleNewValueOptionsLearningDuration {
    fn to_string(&self) -> String {
        match self {
            Self::ZERO_DAYS => String::from("0"),
            Self::ONE_DAY => String::from("1"),
            Self::SEVEN_DAYS => String::from("7"),
        }
    }
}

impl Default for SecurityMonitoringRuleNewValueOptionsLearningDuration {
    fn default() -> SecurityMonitoringRuleNewValueOptionsLearningDuration {
        Self::ZERO_DAYS
    }
}




