/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleNewValueOptionsLearningThreshold : A number of occurrences after which signals will be generated for values that weren't learned.

/// A number of occurrences after which signals will be generated for values that weren't learned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleNewValueOptionsLearningThreshold {
    #[serde(rename = "0")]
    ZERO_OCCURRENCES,
    #[serde(rename = "1")]
    ONE_OCCURRENCE,

}

impl ToString for SecurityMonitoringRuleNewValueOptionsLearningThreshold {
    fn to_string(&self) -> String {
        match self {
            Self::ZERO_OCCURRENCES => String::from("0"),
            Self::ONE_OCCURRENCE => String::from("1"),
        }
    }
}

impl Default for SecurityMonitoringRuleNewValueOptionsLearningThreshold {
    fn default() -> SecurityMonitoringRuleNewValueOptionsLearningThreshold {
        Self::ZERO_OCCURRENCES
    }
}




