/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringFilterAction : The type of filtering action.

/// The type of filtering action.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringFilterAction {
    #[serde(rename = "require")]
    REQUIRE,
    #[serde(rename = "suppress")]
    SUPPRESS,

}

impl ToString for SecurityMonitoringFilterAction {
    fn to_string(&self) -> String {
        match self {
            Self::REQUIRE => String::from("require"),
            Self::SUPPRESS => String::from("suppress"),
        }
    }
}

impl Default for SecurityMonitoringFilterAction {
    fn default() -> SecurityMonitoringFilterAction {
        Self::REQUIRE
    }
}




