/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalsListResponseMetaPage : Paging attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalsListResponseMetaPage {
    /// The cursor used to get the next results, if any. To make the next request, use the same parameters with the addition of the `page[cursor]`.
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
}

impl SecurityMonitoringSignalsListResponseMetaPage {
    /// Paging attributes.
    pub fn new() -> SecurityMonitoringSignalsListResponseMetaPage {
        SecurityMonitoringSignalsListResponseMetaPage {
            after: None,
        }
    }
}


