/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleHardcodedEvaluatorType : Hardcoded evaluator type.

/// Hardcoded evaluator type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleHardcodedEvaluatorType {
    #[serde(rename = "log4shell")]
    LOG4SHELL,

}

impl ToString for SecurityMonitoringRuleHardcodedEvaluatorType {
    fn to_string(&self) -> String {
        match self {
            Self::LOG4SHELL => String::from("log4shell"),
        }
    }
}

impl Default for SecurityMonitoringRuleHardcodedEvaluatorType {
    fn default() -> SecurityMonitoringRuleHardcodedEvaluatorType {
        Self::LOG4SHELL
    }
}




