/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalStateUpdateAttributes : Attributes describing the change of state of a security signal.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalStateUpdateAttributes {
    /// Optional comment to display on archived signals.
    #[serde(rename = "archive_comment", skip_serializing_if = "Option::is_none")]
    pub archive_comment: Option<String>,
    #[serde(rename = "archive_reason", skip_serializing_if = "Option::is_none")]
    pub archive_reason: Option<crate::models::SecurityMonitoringSignalArchiveReason>,
    #[serde(rename = "state")]
    pub state: crate::models::SecurityMonitoringSignalState,
    /// Version of the updated signal. If server side version is higher, update will be rejected.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl SecurityMonitoringSignalStateUpdateAttributes {
    /// Attributes describing the change of state of a security signal.
    pub fn new(state: crate::models::SecurityMonitoringSignalState) -> SecurityMonitoringSignalStateUpdateAttributes {
        SecurityMonitoringSignalStateUpdateAttributes {
            archive_comment: None,
            archive_reason: None,
            state,
            version: None,
        }
    }
}


