/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleSeverity : Severity of the Security Signal.

/// Severity of the Security Signal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleSeverity {
    #[serde(rename = "info")]
    INFO,
    #[serde(rename = "low")]
    LOW,
    #[serde(rename = "medium")]
    MEDIUM,
    #[serde(rename = "high")]
    HIGH,
    #[serde(rename = "critical")]
    CRITICAL,

}

impl ToString for SecurityMonitoringRuleSeverity {
    fn to_string(&self) -> String {
        match self {
            Self::INFO => String::from("info"),
            Self::LOW => String::from("low"),
            Self::MEDIUM => String::from("medium"),
            Self::HIGH => String::from("high"),
            Self::CRITICAL => String::from("critical"),
        }
    }
}

impl Default for SecurityMonitoringRuleSeverity {
    fn default() -> SecurityMonitoringRuleSeverity {
        Self::INFO
    }
}




