/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalIncidentsUpdateRequest : Request body for changing the related incidents of a given security monitoring signal.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalIncidentsUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SecurityMonitoringSignalIncidentsUpdateData>,
}

impl SecurityMonitoringSignalIncidentsUpdateRequest {
    /// Request body for changing the related incidents of a given security monitoring signal.
    pub fn new(data: crate::models::SecurityMonitoringSignalIncidentsUpdateData) -> SecurityMonitoringSignalIncidentsUpdateRequest {
        SecurityMonitoringSignalIncidentsUpdateRequest {
            data: Box::new(data),
        }
    }
}


