/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringStandardRuleQuery : Query for matching rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringStandardRuleQuery {
    #[serde(rename = "aggregation", skip_serializing_if = "Option::is_none")]
    pub aggregation: Option<crate::models::SecurityMonitoringRuleQueryAggregation>,
    /// Field for which the cardinality is measured. Sent as an array.
    #[serde(rename = "distinctFields", skip_serializing_if = "Option::is_none")]
    pub distinct_fields: Option<Vec<String>>,
    /// Fields to group by.
    #[serde(rename = "groupByFields", skip_serializing_if = "Option::is_none")]
    pub group_by_fields: Option<Vec<String>>,
    /// (Deprecated) The target field to aggregate over when using the sum or max aggregations. `metrics` field should be used instead.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    /// Group of target fields to aggregate over when using the sum, max, geo data, or new value aggregations. The sum, max, and geo data aggregations only accept one value in this list, whereas the new value aggregation accepts up to five values.
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<String>>,
    /// Name of the query.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Query to run on logs.
    #[serde(rename = "query")]
    pub query: String,
}

impl SecurityMonitoringStandardRuleQuery {
    /// Query for matching rule.
    pub fn new(query: String) -> SecurityMonitoringStandardRuleQuery {
        SecurityMonitoringStandardRuleQuery {
            aggregation: None,
            distinct_fields: None,
            group_by_fields: None,
            metric: None,
            metrics: None,
            name: None,
            query,
        }
    }
}


