/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalsListResponseLinks : Links attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityMonitoringSignalsListResponseLinks {
    /// The link for the next set of results. **Note**: The request can also be made using the POST endpoint.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl SecurityMonitoringSignalsListResponseLinks {
    /// Links attributes.
    pub fn new() -> SecurityMonitoringSignalsListResponseLinks {
        SecurityMonitoringSignalsListResponseLinks {
            next: None,
        }
    }
}


