/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringSignalState : The new triage state of the signal.

/// The new triage state of the signal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringSignalState {
    #[serde(rename = "open")]
    OPEN,
    #[serde(rename = "archived")]
    ARCHIVED,
    #[serde(rename = "under_review")]
    UNDER_REVIEW,

}

impl ToString for SecurityMonitoringSignalState {
    fn to_string(&self) -> String {
        match self {
            Self::OPEN => String::from("open"),
            Self::ARCHIVED => String::from("archived"),
            Self::UNDER_REVIEW => String::from("under_review"),
        }
    }
}

impl Default for SecurityMonitoringSignalState {
    fn default() -> SecurityMonitoringSignalState {
        Self::OPEN
    }
}




