/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityMonitoringRuleDetectionMethod : The detection method.

/// The detection method.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityMonitoringRuleDetectionMethod {
    #[serde(rename = "threshold")]
    THRESHOLD,
    #[serde(rename = "new_value")]
    NEW_VALUE,
    #[serde(rename = "anomaly_detection")]
    ANOMALY_DETECTION,
    #[serde(rename = "impossible_travel")]
    IMPOSSIBLE_TRAVEL,
    #[serde(rename = "hardcoded")]
    HARDCODED,
    #[serde(rename = "third_party")]
    THIRD_PARTY,

}

impl ToString for SecurityMonitoringRuleDetectionMethod {
    fn to_string(&self) -> String {
        match self {
            Self::THRESHOLD => String::from("threshold"),
            Self::NEW_VALUE => String::from("new_value"),
            Self::ANOMALY_DETECTION => String::from("anomaly_detection"),
            Self::IMPOSSIBLE_TRAVEL => String::from("impossible_travel"),
            Self::HARDCODED => String::from("hardcoded"),
            Self::THIRD_PARTY => String::from("third_party"),
        }
    }
}

impl Default for SecurityMonitoringRuleDetectionMethod {
    fn default() -> SecurityMonitoringRuleDetectionMethod {
        Self::THRESHOLD
    }
}




