/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerTextReplacement : Object describing how the scanned event will be replaced.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerTextReplacement {
    /// Required if type == 'partial_replacement_from_beginning' or 'partial_replacement_from_end'. It must be > 0.
    #[serde(rename = "number_of_chars", skip_serializing_if = "Option::is_none")]
    pub number_of_chars: Option<i64>,
    /// Required if type == 'replacement_string'.
    #[serde(rename = "replacement_string", skip_serializing_if = "Option::is_none")]
    pub replacement_string: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::SensitiveDataScannerTextReplacementType>,
}

impl SensitiveDataScannerTextReplacement {
    /// Object describing how the scanned event will be replaced.
    pub fn new() -> SensitiveDataScannerTextReplacement {
        SensitiveDataScannerTextReplacement {
            number_of_chars: None,
            replacement_string: None,
            r#type: None,
        }
    }
}


