/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerGroupUpdateResponse : Update group response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerGroupUpdateResponse {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::SensitiveDataScannerMetaVersionOnly>>,
}

impl SensitiveDataScannerGroupUpdateResponse {
    /// Update group response.
    pub fn new() -> SensitiveDataScannerGroupUpdateResponse {
        SensitiveDataScannerGroupUpdateResponse {
            meta: None,
        }
    }
}


