/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerStandardPatternData : A standard pattern.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerStandardPatternData {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SensitiveDataScannerStandardPattern>>,
}

impl SensitiveDataScannerStandardPatternData {
    /// A standard pattern.
    pub fn new() -> SensitiveDataScannerStandardPatternData {
        SensitiveDataScannerStandardPatternData {
            data: None,
        }
    }
}


