/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerGroupCreateRequest : Create group request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerGroupCreateRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SensitiveDataScannerGroupCreate>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::SensitiveDataScannerMetaVersionOnly>>,
}

impl SensitiveDataScannerGroupCreateRequest {
    /// Create group request.
    pub fn new() -> SensitiveDataScannerGroupCreateRequest {
        SensitiveDataScannerGroupCreateRequest {
            data: None,
            meta: None,
        }
    }
}


