/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerMetaVersionOnly : Meta payload containing information about the API.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerMetaVersionOnly {
    /// Version of the API (optional).
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl SensitiveDataScannerMetaVersionOnly {
    /// Meta payload containing information about the API.
    pub fn new() -> SensitiveDataScannerMetaVersionOnly {
        SensitiveDataScannerMetaVersionOnly {
            version: None,
        }
    }
}


