/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerConfigurationRelationships : Relationships of the configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerConfigurationRelationships {
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Box<crate::models::SensitiveDataScannerGroupList>>,
}

impl SensitiveDataScannerConfigurationRelationships {
    /// Relationships of the configuration.
    pub fn new() -> SensitiveDataScannerConfigurationRelationships {
        SensitiveDataScannerConfigurationRelationships {
            groups: None,
        }
    }
}


