/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerRuleType : Sensitive Data Scanner rule type.

/// Sensitive Data Scanner rule type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SensitiveDataScannerRuleType {
    #[serde(rename = "sensitive_data_scanner_rule")]
    SENSITIVE_DATA_SCANNER_RULE,

}

impl ToString for SensitiveDataScannerRuleType {
    fn to_string(&self) -> String {
        match self {
            Self::SENSITIVE_DATA_SCANNER_RULE => String::from("sensitive_data_scanner_rule"),
        }
    }
}

impl Default for SensitiveDataScannerRuleType {
    fn default() -> SensitiveDataScannerRuleType {
        Self::SENSITIVE_DATA_SCANNER_RULE
    }
}




