/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerFilter : Filter for the Scanning Group.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerFilter {
    /// Query to filter the events.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

impl SensitiveDataScannerFilter {
    /// Filter for the Scanning Group.
    pub fn new() -> SensitiveDataScannerFilter {
        SensitiveDataScannerFilter {
            query: None,
        }
    }
}


