/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerReorderConfig : Data related to the reordering of scanning groups.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerReorderConfig {
    /// ID of the configuration.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::SensitiveDataScannerConfigurationRelationships>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::SensitiveDataScannerConfigurationType>,
}

impl SensitiveDataScannerReorderConfig {
    /// Data related to the reordering of scanning groups.
    pub fn new() -> SensitiveDataScannerReorderConfig {
        SensitiveDataScannerReorderConfig {
            id: None,
            relationships: None,
            r#type: None,
        }
    }
}


