/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerGroupRelationships : Relationships of the group.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerGroupRelationships {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<crate::models::SensitiveDataScannerConfigurationData>>,
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Box<crate::models::SensitiveDataScannerRuleData>>,
}

impl SensitiveDataScannerGroupRelationships {
    /// Relationships of the group.
    pub fn new() -> SensitiveDataScannerGroupRelationships {
        SensitiveDataScannerGroupRelationships {
            configuration: None,
            rules: None,
        }
    }
}


