/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerRuleCreateRequest : Create rule request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerRuleCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SensitiveDataScannerRuleCreate>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::SensitiveDataScannerMetaVersionOnly>,
}

impl SensitiveDataScannerRuleCreateRequest {
    /// Create rule request.
    pub fn new(data: crate::models::SensitiveDataScannerRuleCreate, meta: crate::models::SensitiveDataScannerMetaVersionOnly) -> SensitiveDataScannerRuleCreateRequest {
        SensitiveDataScannerRuleCreateRequest {
            data: Box::new(data),
            meta: Box::new(meta),
        }
    }
}


