/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerGroupAttributes : Attributes of the Sensitive Data Scanner group.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerGroupAttributes {
    /// Description of the group.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::SensitiveDataScannerFilter>>,
    /// Whether or not the group is enabled.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// Name of the group.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List of products the scanning group applies.
    #[serde(rename = "product_list", skip_serializing_if = "Option::is_none")]
    pub product_list: Option<Vec<crate::models::SensitiveDataScannerProduct>>,
}

impl SensitiveDataScannerGroupAttributes {
    /// Attributes of the Sensitive Data Scanner group.
    pub fn new() -> SensitiveDataScannerGroupAttributes {
        SensitiveDataScannerGroupAttributes {
            description: None,
            filter: None,
            is_enabled: None,
            name: None,
            product_list: None,
        }
    }
}


