/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerGroupData : A scanning group data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerGroupData {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SensitiveDataScannerGroup>>,
}

impl SensitiveDataScannerGroupData {
    /// A scanning group data.
    pub fn new() -> SensitiveDataScannerGroupData {
        SensitiveDataScannerGroupData {
            data: None,
        }
    }
}


