/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerConfigurationType : Sensitive Data Scanner configuration type.

/// Sensitive Data Scanner configuration type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SensitiveDataScannerConfigurationType {
    #[serde(rename = "sensitive_data_scanner_configuration")]
    SENSITIVE_DATA_SCANNER_CONFIGURATIONS,

}

impl ToString for SensitiveDataScannerConfigurationType {
    fn to_string(&self) -> String {
        match self {
            Self::SENSITIVE_DATA_SCANNER_CONFIGURATIONS => String::from("sensitive_data_scanner_configuration"),
        }
    }
}

impl Default for SensitiveDataScannerConfigurationType {
    fn default() -> SensitiveDataScannerConfigurationType {
        Self::SENSITIVE_DATA_SCANNER_CONFIGURATIONS
    }
}




