/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerCreateGroupResponse : Create group response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerCreateGroupResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SensitiveDataScannerGroupResponse>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::SensitiveDataScannerMetaVersionOnly>>,
}

impl SensitiveDataScannerCreateGroupResponse {
    /// Create group response.
    pub fn new() -> SensitiveDataScannerCreateGroupResponse {
        SensitiveDataScannerCreateGroupResponse {
            data: None,
            meta: None,
        }
    }
}


