/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SensitiveDataScannerReorderGroupsResponse : Group reorder response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SensitiveDataScannerReorderGroupsResponse {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::SensitiveDataScannerMeta>>,
}

impl SensitiveDataScannerReorderGroupsResponse {
    /// Group reorder response.
    pub fn new() -> SensitiveDataScannerReorderGroupsResponse {
        SensitiveDataScannerReorderGroupsResponse {
            meta: None,
        }
    }
}


