/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionGetResponse : Get service definition response.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionGetResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::ServiceDefinitionData>>,
}

impl ServiceDefinitionGetResponse {
    /// Get service definition response.
    pub fn new() -> ServiceDefinitionGetResponse {
        ServiceDefinitionGetResponse {
            data: None,
        }
    }
}


