/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2EmailType : Contact type.

/// Contact type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceDefinitionV2EmailType {
    #[serde(rename = "email")]
    EMAIL,

}

impl ToString for ServiceDefinitionV2EmailType {
    fn to_string(&self) -> String {
        match self {
            Self::EMAIL => String::from("email"),
        }
    }
}

impl Default for ServiceDefinitionV2EmailType {
    fn default() -> ServiceDefinitionV2EmailType {
        Self::EMAIL
    }
}




