/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionSchemaVersions : Schema versions

/// Schema versions
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceDefinitionSchemaVersions {
    #[serde(rename = "v1")]
    V1,
    #[serde(rename = "v2")]
    V2,
    #[serde(rename = "v2.1")]
    V2_1,

}

impl ToString for ServiceDefinitionSchemaVersions {
    fn to_string(&self) -> String {
        match self {
            Self::V1 => String::from("v1"),
            Self::V2 => String::from("v2"),
            Self::V2_1 => String::from("v2.1"),
        }
    }
}

impl Default for ServiceDefinitionSchemaVersions {
    fn default() -> ServiceDefinitionSchemaVersions {
        Self::V1
    }
}




