/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Opsgenie : Opsgenie integration for the service.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Opsgenie {
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<crate::models::ServiceDefinitionV2OpsgenieRegion>,
    /// Opsgenie service url.
    #[serde(rename = "service-url")]
    pub service_url: String,
}

impl ServiceDefinitionV2Opsgenie {
    /// Opsgenie integration for the service.
    pub fn new(service_url: String) -> ServiceDefinitionV2Opsgenie {
        ServiceDefinitionV2Opsgenie {
            region: None,
            service_url,
        }
    }
}


