/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Dot1Link : Service's external links.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Dot1Link {
    /// Link name.
    #[serde(rename = "name")]
    pub name: String,
    /// Link provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::ServiceDefinitionV2Dot1LinkType,
    /// Link URL.
    #[serde(rename = "url")]
    pub url: String,
}

impl ServiceDefinitionV2Dot1Link {
    /// Service's external links.
    pub fn new(name: String, r#type: crate::models::ServiceDefinitionV2Dot1LinkType, url: String) -> ServiceDefinitionV2Dot1Link {
        ServiceDefinitionV2Dot1Link {
            name,
            provider: None,
            r#type,
            url,
        }
    }
}


