/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV1 : Deprecated - Service definition V1 for providing additional service metadata and integrations.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV1 {
    #[serde(rename = "contact", skip_serializing_if = "Option::is_none")]
    pub contact: Option<Box<crate::models::ServiceDefinitionV1Contact>>,
    /// Extensions to V1 schema.
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<::std::collections::HashMap<String, serde_json::Value>>,
    /// A list of external links related to the services.
    #[serde(rename = "external-resources", skip_serializing_if = "Option::is_none")]
    pub external_resources: Option<Vec<crate::models::ServiceDefinitionV1Resource>>,
    #[serde(rename = "info")]
    pub info: Box<crate::models::ServiceDefinitionV1Info>,
    #[serde(rename = "integrations", skip_serializing_if = "Option::is_none")]
    pub integrations: Option<Box<crate::models::ServiceDefinitionV1Integrations>>,
    #[serde(rename = "org", skip_serializing_if = "Option::is_none")]
    pub org: Option<Box<crate::models::ServiceDefinitionV1Org>>,
    #[serde(rename = "schema-version")]
    pub schema_version: crate::models::ServiceDefinitionV1Version,
    /// A set of custom tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl ServiceDefinitionV1 {
    /// Deprecated - Service definition V1 for providing additional service metadata and integrations.
    pub fn new(info: crate::models::ServiceDefinitionV1Info, schema_version: crate::models::ServiceDefinitionV1Version) -> ServiceDefinitionV1 {
        ServiceDefinitionV1 {
            contact: None,
            extensions: None,
            external_resources: None,
            info: Box::new(info),
            integrations: None,
            org: None,
            schema_version,
            tags: None,
        }
    }
}


