/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Repo : Service code repositories.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Repo {
    /// Repository name.
    #[serde(rename = "name")]
    pub name: String,
    /// Repository provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Repository URL.
    #[serde(rename = "url")]
    pub url: String,
}

impl ServiceDefinitionV2Repo {
    /// Service code repositories.
    pub fn new(name: String, url: String) -> ServiceDefinitionV2Repo {
        ServiceDefinitionV2Repo {
            name,
            provider: None,
            url,
        }
    }
}


