/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Doc : Service documents.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Doc {
    /// Document name.
    #[serde(rename = "name")]
    pub name: String,
    /// Document provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Document URL.
    #[serde(rename = "url")]
    pub url: String,
}

impl ServiceDefinitionV2Doc {
    /// Service documents.
    pub fn new(name: String, url: String) -> ServiceDefinitionV2Doc {
        ServiceDefinitionV2Doc {
            name,
            provider: None,
            url,
        }
    }
}


