/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV1ResourceType : Link type.

/// Link type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceDefinitionV1ResourceType {
    #[serde(rename = "doc")]
    DOC,
    #[serde(rename = "wiki")]
    WIKI,
    #[serde(rename = "runbook")]
    RUNBOOK,
    #[serde(rename = "url")]
    URL,
    #[serde(rename = "repo")]
    REPO,
    #[serde(rename = "dashboard")]
    DASHBOARD,
    #[serde(rename = "oncall")]
    ONCALL,
    #[serde(rename = "code")]
    CODE,
    #[serde(rename = "link")]
    LINK,

}

impl ToString for ServiceDefinitionV1ResourceType {
    fn to_string(&self) -> String {
        match self {
            Self::DOC => String::from("doc"),
            Self::WIKI => String::from("wiki"),
            Self::RUNBOOK => String::from("runbook"),
            Self::URL => String::from("url"),
            Self::REPO => String::from("repo"),
            Self::DASHBOARD => String::from("dashboard"),
            Self::ONCALL => String::from("oncall"),
            Self::CODE => String::from("code"),
            Self::LINK => String::from("link"),
        }
    }
}

impl Default for ServiceDefinitionV1ResourceType {
    fn default() -> ServiceDefinitionV1ResourceType {
        Self::DOC
    }
}




