/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Integrations : Third party integrations that Datadog supports.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Integrations {
    #[serde(rename = "opsgenie", skip_serializing_if = "Option::is_none")]
    pub opsgenie: Option<Box<crate::models::ServiceDefinitionV2Opsgenie>>,
    /// PagerDuty service URL for the service.
    #[serde(rename = "pagerduty", skip_serializing_if = "Option::is_none")]
    pub pagerduty: Option<String>,
}

impl ServiceDefinitionV2Integrations {
    /// Third party integrations that Datadog supports.
    pub fn new() -> ServiceDefinitionV2Integrations {
        ServiceDefinitionV2Integrations {
            opsgenie: None,
            pagerduty: None,
        }
    }
}


