/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Dot1Slack : Service owner's Slack channel.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Dot1Slack {
    /// Slack Channel.
    #[serde(rename = "contact")]
    pub contact: String,
    /// Contact Slack.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::ServiceDefinitionV2Dot1SlackType,
}

impl ServiceDefinitionV2Dot1Slack {
    /// Service owner's Slack channel.
    pub fn new(contact: String, r#type: crate::models::ServiceDefinitionV2Dot1SlackType) -> ServiceDefinitionV2Dot1Slack {
        ServiceDefinitionV2Dot1Slack {
            contact,
            name: None,
            r#type,
        }
    }
}


