/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Dot1MsTeamsType : Contact type.

/// Contact type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceDefinitionV2Dot1MsTeamsType {
    #[serde(rename = "microsoft-teams")]
    MICROSOFT_TEAMS,

}

impl ToString for ServiceDefinitionV2Dot1MsTeamsType {
    fn to_string(&self) -> String {
        match self {
            Self::MICROSOFT_TEAMS => String::from("microsoft-teams"),
        }
    }
}

impl Default for ServiceDefinitionV2Dot1MsTeamsType {
    fn default() -> ServiceDefinitionV2Dot1MsTeamsType {
        Self::MICROSOFT_TEAMS
    }
}




