/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Dot1Integrations : Third party integrations that Datadog supports.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Dot1Integrations {
    #[serde(rename = "opsgenie", skip_serializing_if = "Option::is_none")]
    pub opsgenie: Option<Box<crate::models::ServiceDefinitionV2Dot1Opsgenie>>,
    #[serde(rename = "pagerduty", skip_serializing_if = "Option::is_none")]
    pub pagerduty: Option<Box<crate::models::ServiceDefinitionV2Dot1Pagerduty>>,
}

impl ServiceDefinitionV2Dot1Integrations {
    /// Third party integrations that Datadog supports.
    pub fn new() -> ServiceDefinitionV2Dot1Integrations {
        ServiceDefinitionV2Dot1Integrations {
            opsgenie: None,
            pagerduty: None,
        }
    }
}


