/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceDefinitionV2Dot1Email : Service owner's email.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceDefinitionV2Dot1Email {
    /// Contact value.
    #[serde(rename = "contact")]
    pub contact: String,
    /// Contact email.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::ServiceDefinitionV2Dot1EmailType,
}

impl ServiceDefinitionV2Dot1Email {
    /// Service owner's email.
    pub fn new(contact: String, r#type: crate::models::ServiceDefinitionV2Dot1EmailType) -> ServiceDefinitionV2Dot1Email {
        ServiceDefinitionV2Dot1Email {
            contact,
            name: None,
            r#type,
        }
    }
}


