/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SlackIntegrationMetadata : Incident integration metadata for the Slack integration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SlackIntegrationMetadata {
    /// Array of Slack channels in this integration metadata.
    #[serde(rename = "channels")]
    pub channels: Vec<crate::models::SlackIntegrationMetadataChannelItem>,
}

impl SlackIntegrationMetadata {
    /// Incident integration metadata for the Slack integration.
    pub fn new(channels: Vec<crate::models::SlackIntegrationMetadataChannelItem>) -> SlackIntegrationMetadata {
        SlackIntegrationMetadata {
            channels,
        }
    }
}


