/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricResponseAttributes : The object describing a Datadog span-based metric.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricResponseAttributes {
    #[serde(rename = "compute", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Box<crate::models::SpansMetricResponseCompute>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::SpansMetricResponseFilter>>,
    /// The rules for the group by.
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<crate::models::SpansMetricResponseGroupBy>>,
}

impl SpansMetricResponseAttributes {
    /// The object describing a Datadog span-based metric.
    pub fn new() -> SpansMetricResponseAttributes {
        SpansMetricResponseAttributes {
            compute: None,
            filter: None,
            group_by: None,
        }
    }
}


