/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansListRequestPage : Paging attributes for listing spans.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansListRequestPage {
    /// List following results with a cursor provided in the previous query.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Maximum number of spans in the response.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl SpansListRequestPage {
    /// Paging attributes for listing spans.
    pub fn new() -> SpansListRequestPage {
        SpansListRequestPage {
            cursor: None,
            limit: None,
        }
    }
}


