/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricUpdateAttributes : The span-based metric properties that will be updated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricUpdateAttributes {
    #[serde(rename = "compute", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Box<crate::models::SpansMetricUpdateCompute>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::SpansMetricFilter>>,
    /// The rules for the group by.
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<crate::models::SpansMetricGroupBy>>,
}

impl SpansMetricUpdateAttributes {
    /// The span-based metric properties that will be updated.
    pub fn new() -> SpansMetricUpdateAttributes {
        SpansMetricUpdateAttributes {
            compute: None,
            filter: None,
            group_by: None,
        }
    }
}


