/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricCreateRequest : The new span-based metric body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SpansMetricCreateData>,
}

impl SpansMetricCreateRequest {
    /// The new span-based metric body.
    pub fn new(data: crate::models::SpansMetricCreateData) -> SpansMetricCreateRequest {
        SpansMetricCreateRequest {
            data: Box::new(data),
        }
    }
}


