/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansListResponse : Response object with all spans matching the request and pagination information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansListResponse {
    /// Array of spans matching the request.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::Span>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::SpansListResponseLinks>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::SpansListResponseMetadata>>,
}

impl SpansListResponse {
    /// Response object with all spans matching the request and pagination information.
    pub fn new() -> SpansListResponse {
        SpansListResponse {
            data: None,
            links: None,
            meta: None,
        }
    }
}


