/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansGroupByTotal : A resulting object to put the given computes in over all the matching records.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansGroupByTotal {
}

impl SpansGroupByTotal {
    /// A resulting object to put the given computes in over all the matching records.
    pub fn new() -> SpansGroupByTotal {
        SpansGroupByTotal {
        }
    }
}


