/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricResponse : The span-based metric object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SpansMetricResponseData>>,
}

impl SpansMetricResponse {
    /// The span-based metric object.
    pub fn new() -> SpansMetricResponse {
        SpansMetricResponse {
            data: None,
        }
    }
}


