/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansComputeType : The type of compute.

/// The type of compute.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpansComputeType {
    #[serde(rename = "timeseries")]
    TIMESERIES,
    #[serde(rename = "total")]
    TOTAL,

}

impl ToString for SpansComputeType {
    fn to_string(&self) -> String {
        match self {
            Self::TIMESERIES => String::from("timeseries"),
            Self::TOTAL => String::from("total"),
        }
    }
}

impl Default for SpansComputeType {
    fn default() -> SpansComputeType {
        Self::TIMESERIES
    }
}




