/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansListRequestData : The object containing the query content.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansListRequestData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SpansListRequestAttributes>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::SpansListRequestType>,
}

impl SpansListRequestData {
    /// The object containing the query content.
    pub fn new() -> SpansListRequestData {
        SpansListRequestData {
            attributes: None,
            r#type: None,
        }
    }
}


