/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricGroupBy : A group by rule.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricGroupBy {
    /// The path to the value the span-based metric will be aggregated over.
    #[serde(rename = "path")]
    pub path: String,
    /// Eventual name of the tag that gets created. By default, the path attribute is used as the tag name.
    #[serde(rename = "tag_name", skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
}

impl SpansMetricGroupBy {
    /// A group by rule.
    pub fn new(path: String) -> SpansMetricGroupBy {
        SpansMetricGroupBy {
            path,
            tag_name: None,
        }
    }
}


