/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansMetricUpdateCompute : The compute rule to compute the span-based metric.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansMetricUpdateCompute {
    /// Toggle to include or exclude percentile aggregations for distribution metrics. Only present when the `aggregation_type` is `distribution`.
    #[serde(rename = "include_percentiles", skip_serializing_if = "Option::is_none")]
    pub include_percentiles: Option<bool>,
}

impl SpansMetricUpdateCompute {
    /// The compute rule to compute the span-based metric.
    pub fn new() -> SpansMetricUpdateCompute {
        SpansMetricUpdateCompute {
            include_percentiles: None,
        }
    }
}


