/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SpansAggregateRequest : The object sent with the request to retrieve a list of aggregated spans from your organization.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpansAggregateRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SpansAggregateData>>,
}

impl SpansAggregateRequest {
    /// The object sent with the request to retrieve a list of aggregated spans from your organization.
    pub fn new() -> SpansAggregateRequest {
        SpansAggregateRequest {
            data: None,
        }
    }
}


