/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamLinkCreate : Team link create



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamLinkCreate {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::TeamLinkAttributes>,
    #[serde(rename = "type")]
    pub r#type: crate::models::TeamLinkType,
}

impl TeamLinkCreate {
    /// Team link create
    pub fn new(attributes: crate::models::TeamLinkAttributes, r#type: crate::models::TeamLinkType) -> TeamLinkCreate {
        TeamLinkCreate {
            attributes: Box::new(attributes),
            r#type,
        }
    }
}


