/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamCreateRelationships : Relationships formed with the team on creation



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamCreateRelationships {
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Box<crate::models::RelationshipToUsers>>,
}

impl TeamCreateRelationships {
    /// Relationships formed with the team on creation
    pub fn new() -> TeamCreateRelationships {
        TeamCreateRelationships {
            users: None,
        }
    }
}


