/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamRelationshipsLinks : Links attributes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamRelationshipsLinks {
    /// Related link.
    #[serde(rename = "related", skip_serializing_if = "Option::is_none")]
    pub related: Option<String>,
}

impl TeamRelationshipsLinks {
    /// Links attributes.
    pub fn new() -> TeamRelationshipsLinks {
        TeamRelationshipsLinks {
            related: None,
        }
    }
}


