/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamCreateRequest : Request to create a team



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamCreateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::TeamCreate>,
}

impl TeamCreateRequest {
    /// Request to create a team
    pub fn new(data: crate::models::TeamCreate) -> TeamCreateRequest {
        TeamCreateRequest {
            data: Box::new(data),
        }
    }
}


