/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamPermissionSettingResponse : Team permission setting response



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamPermissionSettingResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::TeamPermissionSetting>>,
}

impl TeamPermissionSettingResponse {
    /// Team permission setting response
    pub fn new() -> TeamPermissionSettingResponse {
        TeamPermissionSettingResponse {
            data: None,
        }
    }
}


