/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamPermissionSettingsResponse : Team permission settings response



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamPermissionSettingsResponse {
    /// Team permission settings response data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::TeamPermissionSetting>>,
}

impl TeamPermissionSettingsResponse {
    /// Team permission settings response
    pub fn new() -> TeamPermissionSettingsResponse {
        TeamPermissionSettingsResponse {
            data: None,
        }
    }
}


