/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamsResponseLinks : Teams response links.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamsResponseLinks {
    /// First link.
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<String>,
    /// Last link.
    #[serde(rename = "last", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last: Option<Option<String>>,
    /// Next link.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// Previous link.
    #[serde(rename = "prev", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prev: Option<Option<String>>,
    /// Current link.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
}

impl TeamsResponseLinks {
    /// Teams response links.
    pub fn new() -> TeamsResponseLinks {
        TeamsResponseLinks {
            first: None,
            last: None,
            next: None,
            prev: None,
            param_self: None,
        }
    }
}


