/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamUpdateAttributes : Team update attributes



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamUpdateAttributes {
    /// An identifier for the color representing the team
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
    /// Free-form markdown description/content for the team's homepage
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The team's identifier
    #[serde(rename = "handle")]
    pub handle: String,
    /// The name of the team
    #[serde(rename = "name")]
    pub name: String,
}

impl TeamUpdateAttributes {
    /// Team update attributes
    pub fn new(handle: String, name: String) -> TeamUpdateAttributes {
        TeamUpdateAttributes {
            color: None,
            description: None,
            handle,
            name,
        }
    }
}


