/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamPermissionSettingType : Team permission setting type

/// Team permission setting type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamPermissionSettingType {
    #[serde(rename = "team_permission_settings")]
    TEAM_PERMISSION_SETTINGS,

}

impl ToString for TeamPermissionSettingType {
    fn to_string(&self) -> String {
        match self {
            Self::TEAM_PERMISSION_SETTINGS => String::from("team_permission_settings"),
        }
    }
}

impl Default for TeamPermissionSettingType {
    fn default() -> TeamPermissionSettingType {
        Self::TEAM_PERMISSION_SETTINGS
    }
}




