/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TeamPermissionSettingUpdateAttributes : Team permission setting update attributes



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamPermissionSettingUpdateAttributes {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::models::TeamPermissionSettingValue>,
}

impl TeamPermissionSettingUpdateAttributes {
    /// Team permission setting update attributes
    pub fn new() -> TeamPermissionSettingUpdateAttributes {
        TeamPermissionSettingUpdateAttributes {
            value: None,
        }
    }
}


