/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TimeseriesResponseSeries : 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimeseriesResponseSeries {
    /// List of tags that apply to a single response value.
    #[serde(rename = "group_tags", skip_serializing_if = "Option::is_none")]
    pub group_tags: Option<Vec<String>>,
    /// The index of the query in the \"formulas\" array (or \"queries\" array if no \"formulas\" was specified).
    #[serde(rename = "query_index", skip_serializing_if = "Option::is_none")]
    pub query_index: Option<i32>,
    /// Detailed information about the unit. The first element describes the \"primary unit\" (for example, `bytes` in `bytes per second`). The second element describes the \"per unit\" (for example, `second` in `bytes per second`). If the second element is not present, the API returns null.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Vec<crate::models::Unit>>,
}

impl TimeseriesResponseSeries {
    /// 
    pub fn new() -> TimeseriesResponseSeries {
        TimeseriesResponseSeries {
            group_tags: None,
            query_index: None,
            unit: None,
        }
    }
}


