/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTeamAttributes : Team membership attributes



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserTeamAttributes {
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<crate::models::UserTeamRole>>,
}

impl UserTeamAttributes {
    /// Team membership attributes
    pub fn new() -> UserTeamAttributes {
        UserTeamAttributes {
            role: None,
        }
    }
}


