/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTeamUserType : User team user type

/// User team user type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserTeamUserType {
    #[serde(rename = "users")]
    USERS,

}

impl ToString for UserTeamUserType {
    fn to_string(&self) -> String {
        match self {
            Self::USERS => String::from("users"),
        }
    }
}

impl Default for UserTeamUserType {
    fn default() -> UserTeamUserType {
        Self::USERS
    }
}




