/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserUpdateRequest : Update a user.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserUpdateRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::UserUpdateData>,
}

impl UserUpdateRequest {
    /// Update a user.
    pub fn new(data: crate::models::UserUpdateData) -> UserUpdateRequest {
        UserUpdateRequest {
            data: Box::new(data),
        }
    }
}


