/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTeamType : Team membership type

/// Team membership type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserTeamType {
    #[serde(rename = "team_memberships")]
    TEAM_MEMBERSHIPS,

}

impl ToString for UserTeamType {
    fn to_string(&self) -> String {
        match self {
            Self::TEAM_MEMBERSHIPS => String::from("team_memberships"),
        }
    }
}

impl Default for UserTeamType {
    fn default() -> UserTeamType {
        Self::TEAM_MEMBERSHIPS
    }
}




