/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserResponseIncludedItem : An object related to a user.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserResponseIncludedItem {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::RoleAttributes>>,
    /// The unique identifier of the role.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: crate::models::RolesType,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::RoleResponseRelationships>>,
}

impl UserResponseIncludedItem {
    /// An object related to a user.
    pub fn new(r#type: crate::models::RolesType) -> UserResponseIncludedItem {
        UserResponseIncludedItem {
            attributes: None,
            id: None,
            r#type,
            relationships: None,
        }
    }
}


