/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserInvitationRelationships : Relationships data for user invitation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserInvitationRelationships {
    #[serde(rename = "user")]
    pub user: Box<crate::models::RelationshipToUser>,
}

impl UserInvitationRelationships {
    /// Relationships data for user invitation.
    pub fn new(user: crate::models::RelationshipToUser) -> UserInvitationRelationships {
        UserInvitationRelationships {
            user: Box::new(user),
        }
    }
}


