/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserInvitationResponseData : Object of a user invitation returned by the API.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserInvitationResponseData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::UserInvitationDataAttributes>>,
    /// ID of the user invitation.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::UserInvitationRelationships>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::UserInvitationsType>,
}

impl UserInvitationResponseData {
    /// Object of a user invitation returned by the API.
    pub fn new() -> UserInvitationResponseData {
        UserInvitationResponseData {
            attributes: None,
            id: None,
            relationships: None,
            r#type: None,
        }
    }
}


