/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserInvitationData : Object to create a user invitation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserInvitationData {
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::UserInvitationRelationships>,
    #[serde(rename = "type")]
    pub r#type: crate::models::UserInvitationsType,
}

impl UserInvitationData {
    /// Object to create a user invitation.
    pub fn new(relationships: crate::models::UserInvitationRelationships, r#type: crate::models::UserInvitationsType) -> UserInvitationData {
        UserInvitationData {
            relationships: Box::new(relationships),
            r#type,
        }
    }
}


