/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserInvitationsResponse : User invitations as returned by the API.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserInvitationsResponse {
    /// Array of user invitations.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::UserInvitationResponseData>>,
}

impl UserInvitationsResponse {
    /// User invitations as returned by the API.
    pub fn new() -> UserInvitationsResponse {
        UserInvitationsResponse {
            data: None,
        }
    }
}


