/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTeamCreate : A user's relationship with a team



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserTeamCreate {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::UserTeamAttributes>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::UserTeamRelationships>>,
    #[serde(rename = "type")]
    pub r#type: crate::models::UserTeamType,
}

impl UserTeamCreate {
    /// A user's relationship with a team
    pub fn new(r#type: crate::models::UserTeamType) -> UserTeamCreate {
        UserTeamCreate {
            attributes: None,
            relationships: None,
            r#type,
        }
    }
}


