/*
 * Datadog API V2 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTeamPermissionType : User team permission type

/// User team permission type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserTeamPermissionType {
    #[serde(rename = "user_team_permissions")]
    USER_TEAM_PERMISSIONS,

}

impl ToString for UserTeamPermissionType {
    fn to_string(&self) -> String {
        match self {
            Self::USER_TEAM_PERMISSIONS => String::from("user_team_permissions"),
        }
    }
}

impl Default for UserTeamPermissionType {
    fn default() -> UserTeamPermissionType {
        Self::USER_TEAM_PERMISSIONS
    }
}




