name: Publish

permissions: 
  contents: write
  attestations: write
  pull-requests: write

on:
  release:
    types:
      - published

jobs:
  upload_release:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        # Include all history and tags, needed for building the right version
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1.0.0
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - name: Publish tag ${{ github.event.release.tag_name }} crate to crates.io
        env:
          CARGO_REGISTRY_TOKEN: "${{secrets.CRATES_IO_TOKEN}}"
        run: |
          # Get tag name from event
          tag_name="${{ github.event.release.tag_name }}"

          if [[ ! "$tag_name" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            cd $(echo $tag_name | rev | cut -d'/' -f2- | rev)
          fi

          cargo publish --registry crates-io