name: Publish

on:
  release:
    types:
      - published

jobs:
  upload_release:
    name: Upload release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        # Include all history and tags, needed for building the right version
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2

      - name: Publish a Rust crate to crates.io
        env:
          CARGO_REGISTRY_TOKEN: "${{secrets.CRATES_IO_TOKEN}}"
        run: |
          cargo publish --registry crates-io