name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-command:
        description: 'Examples command to execute'
        required: false
        type: string
        default: 'cargo check --examples'
      rust-version:
        description: 'Rust version to use for examples'
        required: false
        type: string
        default: 'stable'
    secrets:
      PIPELINE_GITHUB_APP_ID:
        required: false
      PIPELINE_GITHUB_APP_PRIVATE_KEY:
        required: false

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: DataDog/datadog-api-client-rust
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ inputs.rust-version }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2.0.0
      - name: Check examples
        run: ${{ inputs.examples-command }}
        shell: bash