name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-command:
        description: 'Examples command to execute'
        required: false
        type: string
        default: 'cargo check --examples'
      rust-version:
        description: 'Rust version to use for examples'
        required: false
        type: string
        default: 'stable'
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: DataDog/datadog-api-client-rust
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ inputs.rust-version }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2.9.1
      - name: Check examples
        run: ${{ inputs.examples-command }}
        shell: bash